### ISSUE TITLE
No package available for pip and  python-virtualenvwrapper

### ISSUE THREAD

**Issue by cloudbehl** [Tendrl/node-agent#105]
While trying to follow the steps in the documentation of tendrl-agent the Command[1] mentioned below gives this ouput[2] and I think we need to provide some repo(like EPEL) or some other source so that these packages can be installed.

[1] **Command**
$ sudo yum install python-virtualenv python-virtualenvwrapper python-devel pip

[2] **Traceback(output)**
No package python-virtualenvwrapper available.
No package pip available.

**Comment by r0h4n** [comment]
@TimothyAsir please work with @cloudbehl to fix this

**Comment by anmolsachan** [comment]
Reference : https://packaging.python.org/install_requirements_linux/

1. sudo yum update

2. sudo yum install epel-release

3. sudo yum install python-pip python-virtualenv python-virtualenvwrapper python-devel

This would work.

**Comment by cloudbehl** [comment]
@anmolsachan Yes, I will test it and get back to you. Then we can update readme.

**Comment by r0h4n** [comment]
Is this still valid?
