### ISSUE TITLE
Strange /$HOME directory created by tendrl-noded service

### ISSUE THREAD

**Issue by dahorak** [Tendrl/node-agent#113]
There is a strange `/$HOME` directory on each storage node and it seems to be created by `tendrl-noded` service.
When I remove this directory, while `tendrl-noded` is running, the directory is recreated.
When I remove this directory, while `tendrl-noded` is stopped, the directory is recreated immediately when I start the `tendrl-noded` service, 

```
# tree -a /\$HOME/
/$HOME/
└── .ansible
    └── tmp
        └── ansible-local-15394oux_fe
            └── ansiballz_cache
                └── command-ZIP_STORED

4 directories, 1 file
```

```
# rpm -qa | grep tendrl
tendrl-node-agent-0.0.1-1.el7.centos.noarch
tendrl-gluster-integration-0.0.1-1.el7.centos.noarch
tendrl-common-0.0.1-1.el7.centos.noarch
```

**Comment by mbukatov** [comment]
Is this related to `tendrl_exe_file_prefix` (see https://github.com/Tendrl/node-agent/issues/111)?

**Comment by r0h4n** [comment]
This has been removed, please re-open if exists
