### ISSUE TITLE
version in setup.py is not aligned with git tags

### ISSUE THREAD

**Issue by mbukatov** [Tendrl/node-agent#119]
Version specified in `setup.py` file is `0.0.1`, while the latest git tag (and releases page provided for these tags by github) is `v1.1`.

## Details

```
$ grep version setup.py
    version="0.0.1",
$ git tag
v1.0
v1.1
```

## Related Upstream Guidelines

https://packaging.python.org/distributing/#choosing-a-versioning-scheme
https://packaging.python.org/single_source_version/#single-sourcing-the-version

**Comment by mbukatov** [comment]
The same kind of issue has been found in other components as well:

* https://github.com/Tendrl/gluster_integration/issues/100
* https://github.com/Tendrl/common/issues/90

**Comment by mbukatov** [comment]
The last option listed in [Single-sourcing the Project Version](https://packaging.python.org/single_source_version/#single-sourcing-the-version) looks most interesting:

>  Keep the version number in the tags of a version control system (Git, Mercurial, etc) instead of in the code, and automatically extract it from there using [setuptools_scm](https://pypi.python.org/pypi/setuptools_scm).

**Comment by ktdreyer** [comment]
May I suggest we use the `setup.py` methods we implemented in ceph-installer? We used this with Skyring's agent package, and it really helped to simplify releases. It will make releases more push-button, to avoid these sorts of issues.

**Comment by ktdreyer** [comment]
Mind reviewing the implementation in PR https://github.com/Tendrl/node_agent/pull/125 ? It makes new releases as simple as `python setup.py bump` and `python setup.py release`. You can then build directly from Git, with Copr's Mock SCM build type.
