### ISSUE TITLE
Fix pep8 issues on master

### ISSUE THREAD

**Issue by nthomas-redhat** [Tendrl/node-agent#139]

**Comment by nthomas-redhat** [comment]
@r0h4n , @shtripat Please review

**Comment by mbukatov** [comment]
Current report from pep8 check on master branch has over 1500 lines, see full log from Travis CI here:

https://travis-ci.org/Tendrl/node-agent/jobs/208539987

One can run pep8 check locally as well: `tox -e pep8`
