### ISSUE TITLE
etc directory is incompatible with documentation

### ISSUE THREAD

**Issue by fbalak** [Tendrl/node-agent#155]
According to installation documentation [1] some configuration files from node-agent etc directory should be copied to specific directories but etc directory structure is different from what is specified in documentation.
According to documentation `logging.yaml.timedrotation.sample` should be located at `etc/samples/logging.yaml.timedrotation.sample` but it is located at `etc/tendrl/node-agent/logging.yaml.timedrotation.sample`.
According to documentation there should be `etc/tendrl/tendrl.conf.sample` but there is no such file.
Documentation and etc directory should be united.

[1] https://github.com/Tendrl/node-agent/blob/1399e431b831c2304ea338ba86e1f60d9d1ec831/doc/source/installation.rst

**Comment by fbalak** [comment]
Documentation is corrected in https://github.com/Tendrl/node-agent/commit/1c1e34e87a7689eb98f5f63c8d2e470098f87aab.

**Comment by fbalak** [comment]
In https://github.com/Tendrl/node-agent/blob/32ef41a6c3e14713e837e187276c46cb997159cf/README.rst is still described old procedure for installation with configuration in tendrl.conf. This should be corrected.

**Comment by brainfunked** [comment]
@nnDarshan Please update the documentation with the corrections.

**Comment by nnDarshan** [comment]
@fbalak A fix has been sent to this. Please verify

**Comment by fbalak** [comment]
@nnDarshan `etc/samples/logging.yaml.timedrotation.sample` and `etc/logging.yaml.timedrotation.sample` in https://github.com/Tendrl/node-agent/blob/1c1e34e87a7689eb98f5f63c8d2e470098f87aab/doc/source/installation.rst are not unified with content of `etc` directory.
