### ISSUE TITLE
Inventory refresh messages need to be logged as DEBUG and should include outcome

### ISSUE THREAD

**Issue by brainfunked** [Tendrl/node-agent#192]
Messages are currently logged at INFO for inventory refresh. These messages flood the logs. Here's what needs to happen instead:

* The first inventory sync upon startup needs to be logged under INFO.
* Every periodic sync apart from the first needs to be logged under DEBUG.
* If any inventory details were detected to be changed, they need to be logged under INFO. This could be part of the same message or another message. The diff of the changes should be logged in the same message.
* Any message saying that the inventory hasn't changed needs to be under DEBUG.

**Comment by nnDarshan** [comment]
The current node_agent has old style logging...This is going to change as we are using the Message() and Event() style of logging. @anmolsachan has a patch for that.
I feel this issue can be fixed as part of that patch

**Comment by anmolsachan** [comment]
Yes, I can add this to the pr. Should I go ahead with incorporating this ?

**Comment by nnDarshan** [comment]
@anmolsachan Please add this change as well in your PR

**Comment by anmolsachan** [comment]
@brainfunked Points 1 & 2 listed in the issue have been merged in logging pr's. Regarding points 3 & 4, currently we are not have any mechanism to detect the changes in node inventory. And Moreover the similar thing will have to be done in integration repos also. Should I take this up as a separate spec and implement some kind of generic logic ? Please suggest how should I about it.

**Comment by r0h4n** [comment]
@brainfunked closing this one, please collaborate with @anmolsachan for remaining new changes
