### ISSUE TITLE
packages required for ssh_key configuration

### ISSUE THREAD

**Issue by GowthamShanmugam** [Tendrl/node-agent#234]
For ssh-key configuration needs two different packages called psutil and libselinux-python

psutil used to find sshd service status and port using process id (pip package)
libselinux-python gives support at the time of copying authorize key (yum package)

But these two packages names are differ in cent os and rhel
in rhel package name is python-psutil, libselinux

**Comment by GowthamShanmugam** [comment]
@TimothyAsir @brainfunked  @r0h4n @shtripat @nnDarshan 
code ref: https://github.com/Tendrl/commons/pull/176,   https://github.com/Tendrl/node-agent/pull/233

**Comment by mbukatov** [comment]
I wonder how psutil is actually used. When I grep sources of tendrl-node-agent for it, I don't find anything.

**Comment by r0h4n** [comment]
@mbukatov you are correct, psutil is used here https://github.com/Tendrl/commons/pull/175

and the requirement for psutil should be on tendrl-commons and not on tendrl-node-agent. This a newly introduced issue. I will fix it

**Comment by GowthamShanmugam** [comment]
@r0h4n Tendrl/commons#175 this is job_class patch here psutil not used

**Comment by r0h4n** [comment]
Sorry, the correct PR is https://github.com/Tendrl/commons/pull/176

**Comment by GowthamShanmugam** [comment]
@mbukatov @r0h4n i have raised this issue wrongly 

both centos and  rhel yum package have same name psutil only i am confused with pip and yum package. 

Now wen no need to worry about libselinux-python, because i have mentioned in spec selinux should be disable for ssh_util config patch. 

We can close this bug i feel, yours suggestion please
