### ISSUE TITLE
Hidden dependency on psutil

### ISSUE THREAD

**Issue by fbalak** [Tendrl/node-agent#237]
`tendrl-node-agent` service fails after installation because of unspecified requirement on `psutil`.

`# systemctl status tendrl-node-agent`
● tendrl-node-agent.service - A python agent local to every managed storage node in the sds cluster
   Loaded: loaded (/usr/lib/systemd/system/tendrl-node-agent.service; enabled; vendor preset: disabled)
   Active: failed (Result: start-limit) since Mon 2017-03-06 14:47:30 UTC; 5min ago
 Main PID: 20744 (code=exited, status=1/FAILURE)

```
Mar 06 14:47:30 hostname systemd[1]: tendrl-node-agent.service: main process exited, code=exited, status=1/FAILURE
Mar 06 14:47:30 hostname systemd[1]: Unit tendrl-node-agent.service entered failed state.
Mar 06 14:47:30 hostname systemd[1]: tendrl-node-agent.service failed.
Mar 06 14:47:30 hostname systemd[1]: tendrl-node-agent.service holdoff time over, scheduling restart.
Mar 06 14:47:30 hostname systemd[1]: start request repeated too quickly for tendrl-node-agent.service
Mar 06 14:47:30 hostname systemd[1]: Failed to start A python agent local to every managed storage node in the sds cluster.
Mar 06 14:47:30 hostname systemd[1]: Unit tendrl-node-agent.service entered failed state.
Mar 06 14:47:30 hostname systemd[1]: tendrl-node-agent.service failed.
```

`# journalctl _PID=20744`
```
-- Logs begin at Mon 2017-03-06 14:28:45 UTC, end at Mon 2017-03-06 14:53:13 UTC. --
Mar 06 14:47:30 hostname tendrl-node-agent[20744]: Traceback (most recent call last):
Mar 06 14:47:30 hostname tendrl-node-agent[20744]: File "/usr/bin/tendrl-node-agent", line 5, in <module>
Mar 06 14:47:30 hostname tendrl-node-agent[20744]: from pkg_resources import load_entry_point
Mar 06 14:47:30 hostname tendrl-node-agent[20744]: File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 3007, in <module>
Mar 06 14:47:30 hostname tendrl-node-agent[20744]: working_set.require(__requires__)
Mar 06 14:47:30 hostname tendrl-node-agent[20744]: File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 728, in require
Mar 06 14:47:30 hostname tendrl-node-agent[20744]: needed = self.resolve(parse_requirements(requirements))
Mar 06 14:47:30 hostname tendrl-node-agent[20744]: File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 626, in resolve
Mar 06 14:47:30 hostname tendrl-node-agent[20744]: raise DistributionNotFound(req)
Mar 06 14:47:30 hostname tendrl-node-agent[20744]: pkg_resources.DistributionNotFound: psutil
```

Tested with:
tendrl-node-monitoring-1.2.1-03_06_2017_00_37_02.noarch
tendrl-commons-1.2.1-2.el7.centos.noarch
tendrl-node-agent-1.2.1-03_06_2017_19_00_14.noarch
tendrl-gluster-integration-1.2.1-03_05_2017_04_38_02.noarch

**Comment by mbukatov** [comment]
This looks related to https://github.com/Tendrl/node-agent/issues/234

**Comment by sankarshanmukhopadhyay** [comment]
This is listed under https://github.com/Tendrl/usmqe-tests/wiki#blockers @GowthamShanmugam @r0h4n @TimothyAsir please comment and update.

**Comment by TimothyAsir** [comment]
@GowthamShanmugam please add Required: psutil in the spec to fix this issue

**Comment by mbukatov** [comment]
Just a note (to prevent confusion): @r0h4n points out in https://github.com/Tendrl/node-agent/issues/234#issuecomment-284425657 that this dependency should be dropped from tendrl-node-agent and moved into tendrl-commons and that he will handle it.

**Comment by GowthamShanmugam** [comment]
@TimothyAsir @sankarshanmukhopadhyay  @r0h4n psutil is actually a dependency for common, so i removed psutil from node-agent and added in common setup.py and i have also added in Required section in sepc file 

pr is under review: 
common - https://github.com/Tendrl/commons/pull/184
node-agent: https://github.com/Tendrl/node-agent/pull/242

**Comment by fbalak** [comment]
It seems ok. Tested with:
tendrl-commons-1.2.1-03_08_2017_04_42_04.noarch
tendrl-node-agent-1.2.1-03_08_2017_00_01_03.noarch
