### ISSUE TITLE
TTL on the message directories

### ISSUE THREAD

**Issue by brainfunked** [Tendrl/node-agent#251]
The message directories used for logging messages in etcd need to have a configurable TTL. Given the nature of etcd, it is necessary to expire old data periodically. The default interval could be something like 2 days. However, the interval needs to be administrator configurable, depending upon the memory available and the size of the cluster etc.

**Comment by GowthamShanmugam** [comment]
i am working on this

**Comment by shtripat** [comment]
One thought here.

time to live is I feel the simplest way to handle data load on central store.
But actual live scenario it should more be policy driven. For example, user should be able to decide what to do we audit log, operational flow data etc which are older than certain time. Few options could be as below

- Move the records to a different etcd instance which is archive of such old details. This could used later if required for audit purpose. This archive etcd instance maintains the same structure as of tendrl central store.
- Move the older details in the form of json dumps to external (configured) location. Optionally the the json dump files could be archived in the form of TAR files with date time stamp attached to name. This could later in imported in an etcd instance for reference

@Tendrl/tendrl-core comments? I feel this should be our ultimate goal.

**Comment by GowthamShanmugam** [comment]
ttl is deleting only entries in the path but directories are not deleted, it show empty directory

**Comment by GowthamShanmugam** [comment]
PR is under review

**Comment by GowthamShanmugam** [comment]
Patch for assigning TTL to message and job_updates are done.

**Comment by nthomas-redhat** [comment]
closing this as fix is merged
