### ISSUE TITLE
admin node agent and definition recompilation

### ISSUE THREAD

**Issue by brainfunked** [Tendrl/node-agent#253]
The node agent deployed on the API node, in non co-located scenarios would not be involved in any clusters. Such a node agent (or more than one) could be tagged as an administrative node agent. The administrative agents would be the primary recipients of jobs related to definition recompilation. This could accomplished using an admin tag and correspondingly routed flows.

The definition compilation is currently done only on startup. The admin node agent could run a watch thread to check for any updates to the definition files and trigger jobs for recompilation. It should also be possible to trigger such a job externally, when an add-on stack adds or updates it's own definition files.

**Comment by r0h4n** [comment]
Update: Apart from the Admin triggering the recompilation job, rest of the mentioned items are finished

**Comment by r0h4n** [comment]
After looking at current scope of definitions and Tendrl features, we do not require periodic re-aggregation of definitions provided by various namespaces. (which are per process and not shared)
