### ISSUE TITLE
Disk_id is changing when reboot the node

### ISSUE THREAD

**Issue by GowthamShanmugam** [Tendrl/node-agent#295]
We are stored all disks using some id which is provided by hwinfo:
for example i have 4 disks in my setup like:
vda                 252:0    0   15G  0 disk 
├─vda1              252:1    0    1G  0 part /boot
└─vda2              252:2    0   14G  0 part 
  ├─cl_network-root 253:0    0 12.5G  0 lvm  /
  └─cl_network-swap 253:1    0  1.5G  0 lvm  [SWAP]
vdd                 252:48   0   20G  0 disk 
vde                 252:64   0   20G  0 disk 
vdf                 252:80   0   20G  0 disk 
├─vdf1              252:81   0   15G  0 part 
└─vdf2              252:82   0  5.1G  0 part 
vdg                 252:96   0   20G  0 disk 
├─vdg1              252:97   0   15G  0 part 
└─vdg2   

Then i deactivate vdd, vde, vdg
Now disks are like : 
vda                 252:0    0   15G  0 disk 
├─vda1              252:1    0    1G  0 part /boot
└─vda2              252:2    0   14G  0 part 
  ├─cl_network-root 253:0    0 12.5G  0 lvm  /
  └─cl_network-swap 253:1    0  1.5G  0 lvm  [SWAP]
vdf                 252:80   0   20G  0 disk 
├─vdf1              252:81   0   15G  0 part 
└─vdf2              252:82   0  5.1G  0 part 
i have checked etcd vdf1 and vdf2 have disks id like 
   for  /dev/vdf1 - HEZP.SE1wIdpsiiC
   for  /dev/vdf2 - kPpT.SE1wIdpsiiC

After that i have restarted node and then i have checked again using lsblk
vda                 252:0    0   15G  0 disk 
├─vda1              252:1    0    1G  0 part /boot
└─vda2              252:2    0   14G  0 part 
  ├─cl_network-root 253:0    0 12.5G  0 lvm  /
  └─cl_network-swap 253:1    0  1.5G  0 lvm  [SWAP]
vdb                 252:16   0   20G  0 disk 
├─vdb1              252:17   0   15G  0 part /var/lib/ceph/tmp/mnt.x2dJVf
└─vdb2              252:18   0  5.1G  0 part
Now vdf become vdb, i have checked etcd, disk id for vdb and it partitions are changed. It took old vdb and its partitions ids.

**Comment by GowthamShanmugam** [comment]
@shtripat @r0h4n @nnDarshan @brainfunked your suggestions please

**Comment by GowthamShanmugam** [comment]
@mbukatov

**Comment by mbukatov** [comment]
@GowthamShanmugam Hmm, I have no idea what properties ids provided by hwinfo have, quick look into manpage didn't help. Without understanding this, it's not very wise to use it for something ...

That said, look at [Persistent Naming](https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Storage_Administration_Guide/persistent_naming.html) chapter from RHEL 7 Admin Guide, it provides details about naming block devices and which one to use when persistence is needed.

**Comment by GowthamShanmugam** [comment]
@mbukatov ok

**Comment by nnDarshan** [comment]
Solution approach for gluster:
In case of gluster, we can maintain the list of bricks at "clusters/<cluster_id>/nodes/<node_id>/Raw_bricks/" Here we can store all the bricks that we created so that volume creation flow can fetch the list of free bricks from here.
Each brick under this will initially contain the name of the brick as provided by user and mount point that was provided by the user. Gluster integration service has to update other brick details periodically by using the mount point that is mentioned here. Since mountpoint does not change even after reboot. If we sync the mount point details periodically. the underlying device detail for the brick will be kept updated even if it changes after a reboot.
With this approach, we will not have the problem of names changing after reboot

@nthomas-redhat @shtripat Please provide your inputs

**Comment by shtripat** [comment]
@nnDarshan I have a question. So once the brick are used for volume creation, do we still retain the entries here or delete?
If we retain, then calling it as `RawBricks` is not correct.

**Comment by nnDarshan** [comment]
@shtripat Yes we retain this detail even after brick creation. Because we will be referring this to get the backend device used for this brick.
I agree the name RawBrick doesnt seem right. Can we call it BackendBricks or GlutsterBricks?

**Comment by shtripat** [comment]
@nnDarshan to me `NodeBricks` looks more prominent.
@Tendrl/tendrl-core comments?

**Comment by nthomas-redhat** [comment]
Impact should be analysed for ceph use case as well.
@nnDarshan once you handle the gluster use case, please link the PR here

**Comment by r0h4n** [comment]
@nnDarshan @GowthamShanmugam any updates on this?

**Comment by r0h4n** [comment]
@GowthamShanmugam @nnDarshan Any updates?

**Comment by GowthamShanmugam** [comment]
@r0h4n i had discuss with @nnDarshan he said this we have to do brick syn in gluster cluster so it will sovle this problem in gluster side, @nthomas-redhat is it affect ceph side?

**Comment by r0h4n** [comment]
@brainfunked Please provide the disk inventory inputs you had planned few weeks back

**Comment by r0h4n** [comment]
@GowthamShanmugam Whats the update on this one?

**Comment by GowthamShanmugam** [comment]
This issue is fixed we can close this
