### ISSUE TITLE
python-hwinfo package  which is used in setup.py not same as what we are excepting 

### ISSUE THREAD

**Issue by GowthamShanmugam** [Tendrl/node-agent#296]
python-hwinfo package which is used inside setup.py is giving different output format. This package outputs and command are different from what we are using now.

**Comment by GowthamShanmugam** [comment]
@r0h4n @shtripat @r0h4n @TimothyAsir  hwinfo in rpm build is correct but pip package which is used inside setup.py is wrong.

**Comment by r0h4n** [comment]
Fixed
