### ISSUE TITLE
Remove Node object definition from node-agent definition file as the object is moved to commons now

### ISSUE THREAD

**Issue by anmolbabu** [Tendrl/node-agent#311]
1. Node object definition and its atoms are moved to commons.
2. Node-agent definition file still contains Node object definition and its associated atoms declarations
3. ImportCluster flow in Node-agent definition file refers to an non-existant command atom. It should rather refer to command atom in commons..

**Comment by anmolbabu** [comment]
@r0h4n As discussed I have raised this issue

**Comment by nthomas-redhat** [comment]
Closing this as the PR is already merged
