### ISSUE TITLE
Definitions file does not have required attribute integration_id

### ISSUE THREAD

**Issue by anivargi** [Tendrl/node-agent#324]
`https://github.com/Tendrl/node-agent/blob/develop/tendrl/integrations/ceph/objects/definition/ceph.yaml#L17` requires `TendrlContext.integration_id` but is not defined as a attribute in the TendrlContext `attrs` section at https://github.com/Tendrl/node-agent/blob/develop/tendrl/integrations/ceph/objects/definition/ceph.yaml#L37

**Comment by anivargi** [comment]
Similarly for gluster.

**Comment by r0h4n** [comment]
Fixed: https://github.com/Tendrl/node-agent/commit/aba3573b2e1d5a43d5281a8f6f2ee79f30d3dcb8
