### ISSUE TITLE
clustere is not detected

### ISSUE THREAD

**Issue by mkudlej** [Tendrl/node-agent#370]
I've installed Tendrl packages(except of ceph and gluster integration) first and then I've installed Ceph on some nodes. I don't see in new Ceph cluster in Tendrl API function calls(GetNodeList | jq ".clusters"). I think that clusters installed on nodes where Tendrl node agent is already installed should be detected and user should be asked for importing them.

**Comment by mkudlej** [comment]
Server:
```
etcd-3.1.0-2.el7.x86_64
python-etcd-0.4.3-1.noarch
rubygem-etcd-0.3.0-1.el7.centos.noarch
tendrl-api-1.2.2-04_06_2017_01_51_04.noarch
tendrl-api-doc-1.2.2-04_06_2017_01_51_04.noarch
tendrl-api-httpd-1.2.2-04_06_2017_01_51_04.noarch
tendrl-commons-1.2.2-04_06_2017_04_42_05.noarch
tendrl-dashboard-1.2.1-04_06_2017_10_49_10.noarch
tendrl-node-agent-1.2.2-04_06_2017_00_01_33.noarch
tendrl-performance-monitoring-1.2.2-04_06_2017_03_02_03.noarch
```

nodes:
```
centos-release-ceph-jewel-1.0-1.el7.centos.noarch
ceph-base-10.2.3-0.el7.x86_64
ceph-common-10.2.3-0.el7.x86_64
ceph-mon-10.2.3-0.el7.x86_64
ceph-selinux-10.2.3-0.el7.x86_64
libcephfs1-10.2.3-0.el7.x86_64
python-cephfs-10.2.3-0.el7.x86_64
tendrl-commons-1.2.2-04_06_2017_04_42_05.noarch
tendrl-node-agent-1.2.2-04_06_2017_00_01_33.noarch
tendrl-node-monitoring-1.2.2-04_06_2017_00_37_03.noarch
```
There is ceph cluster which was not detected by Tendrl:
```
ceph -c /etc/ceph/test_name.conf -s
    cluster 3524256a-3302-4c13-8cb2-e7f167a23fd3
     health HEALTH_WARN
            too few PGs per OSD (4 < min 30)
     monmap e1: 3 mons at {mkudlej-usm1-mon1=10.34.108.75:6789/0,mkudlej-usm1-mon2=10.34.108.78:6789/0,mkudlej-usm1-mon3=10.34.108.86:6789/0}
            election epoch 12, quorum 0,1,2 mkudlej-usm1-mon1,mkudlej-usm1-mon2,mkudlej-usm1-mon3
     osdmap e117: 40 osds: 40 up, 40 in
            flags sortbitwise
      pgmap v174: 64 pgs, 1 pools, 0 bytes data, 0 objects
            1439 MB used, 34597 GB / 34599 GB avail
                  64 active+clean
```

**Comment by shtripat** [comment]
@mkudlej I have tried this scenario with gluster at least. I had tendrl-node-agent running on the node but no gluster/ceph bits installed. Initially the `DetectedCluster` field was missing for the node in etcd.
Afterwards I installed gluster bits on the nodes, and after few seconds `DetectedCluster` gets populated for the node entry in etcd. So backend seems to be working as expected.

@mkudlej plz confirm the `DetectedCluster` field availability in etcd at least for the node. If its present the @anivargi plz check api layer.

**Comment by GowthamShanmugam** [comment]
@mbukatov @shtripat i have tested for ceph cluster, detected cluster is populated sucessfully,
"detectedcluster": {
        "detected_cluster_id": "0bdcc8f4-cbc9-4ead-93f7-1a4334f58f56",
        "detected_cluster_name": "ceph",
        "sds_pkg_name": "ceph",
        "sds_pkg_version": "10.2.3"
      }

how i tested:
   -  I have created 5 fresh machine with centos 7.3  (3 mon 2 osds)
   -  Then i have installed all the tendrl packages what you mentioned above except ceph-integration
     - Then i have started node-agent on all the machines.
     - i have created configured 6th machine for provisioning purpose 
     - i have created ceph cluster using ceph-ansible from provisioning node
     - when cluster is created node-agents in mon machines are updates detected cluster information in etcd
     - Then i have used api to fetch node details, there also i saw detected cluster details.
   curl -H 'Content-Type: application/json' -H 'Authorization: Bearer 4c95a9de5566dbec8bdff73dbf45e509ef8d68a3af201169607081c02da5171d' -XGET http://10.70.42.104/api/1.0/GetNodeList

**Comment by mkudlej** [comment]
I've tested with (server):
```
ceph-ansible-2.2.0-0.rc1.87.ge2c8f1a.el7.noarch
ceph-installer-1.2.2-23.g19ec4f5.el7.noarch
etcd-3.1.0-2.el7.x86_64
python-etcd-0.4.3-1.noarch
rubygem-etcd-0.3.0-1.el7.centos.noarch
tendrl-api-1.2.2-04_10_2017_01_51_03.noarch
tendrl-api-doc-1.2.2-04_10_2017_01_51_03.noarch
tendrl-api-httpd-1.2.2-04_10_2017_01_51_03.noarch
tendrl-commons-1.2.2-04_10_2017_04_42_05.noarch
tendrl-dashboard-1.2.1-04_10_2017_04_11_04.noarch
tendrl-node-agent-1.2.2-04_10_2017_00_01_03.noarch
tendrl-performance-monitoring-1.2.2-04_10_2017_03_02_03.noarch
```

(ceph node):
```
centos-release-ceph-jewel-1.0-1.el7.centos.noarch
ceph-base-10.2.3-0.el7.x86_64
ceph-common-10.2.3-0.el7.x86_64
ceph-fuse-10.2.3-0.el7.x86_64
ceph-mds-10.2.3-0.el7.x86_64
ceph-mon-10.2.3-0.el7.x86_64
ceph-osd-10.2.3-0.el7.x86_64
ceph-selinux-10.2.3-0.el7.x86_64
libcephfs1-10.2.3-0.el7.x86_64
python-cephfs-10.2.3-0.el7.x86_64
python-etcd-0.4.3-1.noarch
tendrl-ceph-integration-1.2.2-04_10_2017_06_35_03.noarch
tendrl-commons-1.2.2-04_10_2017_04_42_05.noarch
tendrl-node-agent-1.2.2-04_10_2017_00_01_03.noarch
tendrl-node-monitoring-1.2.2-04_10_2017_00_37_03.noarch
```

and it works. -->close
