### ISSUE TITLE
Storage node with no gluster service running is incorrectly identified as part of trusted pool

### ISSUE THREAD

**Issue by japplewhite** [Tendrl/node-agent#396]
I have a tendrl server with two centos 7 blank nodes attached and running 
tendrl-apid.service
tendrl-node-agent.service
tendrl-performance-monitoring.service
tendrl-node-agent.socket
configured as per rpm instructions.

I go into the UI for the first time and the nodes show up as gluster peers ready for import.
ID: 32a85679d0c6448f367c6d90d99fbbf2cdc754a5393ac8f1dcb3058b0963b6d3
Storage Service: Glusterfs 3.10.1

**Comment by nthomas-redhat** [comment]
@japplewhite gluster installed on the nodes?

**Comment by shtripat** [comment]
@Jeff also if we get access to the setup for debugging would be better.

**Comment by shtripat** [comment]
@Jeff I tried in a fresh setup without having gluster bits or tendrl-gluster-integration installed on nodes. At least the API doesnot return `DetectedCluster` values for the nodes.

I suspect in your setup nodes would have been part of gluster cluster earlier and without cleanup of etcd again you are checking the nodes. Old node entities details in etcd might be having `DetectedCluster` populated and so the issue.

You can verify the same by checking `http://{etcd node}:2379/v2/keys/nodes/{node-id}`. These URLs should not have `DetectedCluster` populated if no storage bits installed on the nodes.

Also please share the setup details through mail and we can verify it.

**Comment by r0h4n** [comment]
Any updates on this @japplewhite ?

**Comment by anmolbabu** [comment]
I faced this today and node-agent kept complaining the following:

{u'publisher': u'node_agent', u'job_id': u'', u'timestamp': u'2017-05-07 07:44:07.257827+00:00', u'caller': {u'function': u'_derive_cluster_id', u'line_no': u'25', u'filename': u'/usr/lib/python2.7/site-packages/tendrl/node_agent/discovery/sds/plugins/discover_gluster_sds_details.py'}, u'updated_at': u'2017-05-07 07:44:07.451160+00:00', u'message_id': u'dd5a02c8-73bf-410b-bd0e-b2ddf90f9414', u'priority': u'error', u'parent_id': u'', u'node_id': u'5f08cf57-c9b4-4cc6-a8d6-3bcdcfe5c296', u'cluster_id': u'', u'flow_id': u'', u'payload': {u'message': u'Error formulating cluster_id'}}

under /messages/events in etcd.

**Comment by r0h4n** [comment]
@anmolbabu "Error formulating cluster_id"  expected when gluster service is not running and no pool is found. 

Gluster pool list is expected to return the list trusted storage pools (i.e. Tendrl managed nodes).

So does Tendrl take responsibility of adding nodes to gluster storage pool by running command "gluster peer probe" ?

**Comment by r0h4n** [comment]
I have made improvements to the gluster detection code 
https://github.com/Tendrl/node-agent/commit/446572dcef868a9d8327245a8e108ec0e118525c

**Comment by anmolbabu** [comment]
@r0h4n My only doubt is -- Is absence of cluster on a node managed by tendrl considered a case of an error then?? Because it is reported as such.

**Comment by r0h4n** [comment]
Every tendrl managed gluster node needs to be made part of  "gluster pool list" 

The user has to perform "gluster peer probe"  on each node in cluster for all other nodes, 

@brainfunked @japplewhite Tendrl can create this peer group automatically based on the sds_version i.e. nodes with same version of gluster rpm  will be considered as part of a single detected cluster

**Comment by japplewhite** [comment]
@r0h4n Let's keep this clean. For RHEL or CentOS nodes that are imported we should not presume to know what the user intends to do with them. If they select them for installation of Ceph or Gluster then we use that flow to make them either type of cluster. If not they stay as spares and we should still report their basic hardware characteristics so the user can decide whether they are mons, osds, etc. Make sense?

**Comment by r0h4n** [comment]
For being detected by tendrl-node-agent, a node has to be part of the gluster trusted storage pool.

Thats the only pre-requisite for now
