### ISSUE TITLE
Node agent has high cpu usage

### ISSUE THREAD

**Issue by japplewhite** [Tendrl/node-agent#397]
CPU at idle is between 65 and 90%.
Strace on the pid shows a repeating pattern of hitting /dev/urandom and a queue in etcd:

close(11)                               = 0
gettid()                                = 10783
stat("/usr/lib/python2.7/site-packages/tendrl/commons/message.py", {st_mode=S_IFREG|0644, st_size=6159, ...}) = 0
stat("/usr/lib/python2.7/site-packages/tendrl/commons/message.py", {st_mode=S_IFREG|0644, st_size=6159, ...}) = 0
stat("/usr/lib/python2.7/site-packages/tendrl/commons/etcdobj/__init__.py", {st_mode=S_IFREG|0644, st_size=8714, ...}) = 0
stat("/usr/lib/python2.7/site-packages/tendrl/commons/etcdobj/__init__.py", {st_mode=S_IFREG|0644, st_size=8714, ...}) = 0
stat("/usr/lib/python2.7/site-packages/tendrl/commons/objects/__init__.py", {st_mode=S_IFREG|0644, st_size=7108, ...}) = 0
stat("/usr/lib/python2.7/site-packages/tendrl/commons/objects/__init__.py", {st_mode=S_IFREG|0644, st_size=7108, ...}) = 0
stat("/usr/lib/python2.7/site-packages/tendrl/commons/jobs/__init__.py", {st_mode=S_IFREG|0644, st_size=6243, ...}) = 0
stat("/usr/lib/python2.7/site-packages/tendrl/commons/jobs/__init__.py", {st_mode=S_IFREG|0644, st_size=6243, ...}) = 0
stat("/usr/lib64/python2.7/site-packages/gevent/greenlet.py", {st_mode=S_IFREG|0644, st_size=15658, ...}) = 0
stat("/usr/lib64/python2.7/site-packages/gevent/greenlet.py", {st_mode=S_IFREG|0644, st_size=15658, ...}) = 0
stat("/usr/lib/python2.7/site-packages/tendrl/commons/etcdobj/__init__.py", {st_mode=S_IFREG|0644, st_size=8714, ...}) = 0
stat("/usr/lib/python2.7/site-packages/tendrl/commons/etcdobj/__init__.py", {st_mode=S_IFREG|0644, st_size=8714, ...}) = 0
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=118, ...}) = 0
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=118, ...}) = 0
epoll_ctl(4, EPOLL_CTL_ADD, 6, {EPOLLIN, {u32=6, u64=12884901894}}) = -1 EEXIST (File exists)
epoll_wait(4, {{EPOLLIN|EPOLLHUP, {u32=9, u64=51715701211145}}, {EPOLLHUP, {u32=12, u64=51522427682828}}}, 64, 1) = 2
epoll_ctl(4, EPOLL_CTL_MOD, 9, {EPOLLIN, {u32=9, u64=51715701211145}}) = 0
epoll_ctl(4, EPOLL_CTL_MOD, 12, {EPOLLIN, {u32=12, u64=51522427682828}}) = 0
sendto(6, "GET /v2/keys/queue/4d2fcc2f-19e8"..., 135, 0, NULL, 0) = 135
fcntl(6, F_GETFL)                       = 0x802 (flags O_RDWR|O_NONBLOCK)
fcntl(6, F_SETFL, O_RDWR|O_NONBLOCK)    = 0
recvfrom(6, "HTTP/1.1 200 OK\r\nContent-Type: a"..., 8192, 0, NULL, NULL) = 353
open("/dev/urandom", O_RDONLY|O_CLOEXEC) = 11
fcntl(11, F_GETFD)                      = 0x1 (flags FD_CLOEXEC)
fcntl(11, F_SETFD, FD_CLOEXEC)          = 0
getuid()                                = 0
getppid()                               = 1
read(11, "\373\374\262\33\303\253\354By\257F}$\202\226\331", 16) = 16
close(11)                               = 0
gettid()                                = 10783
stat("/usr/lib/python2.7/site-packages/tendrl/commons/message.py", {st_mode=S_IFREG|0644, st_size=6159, ...}) = 0
stat("/usr/lib/python2.7/site-packages/tendrl/commons/message.py", {st_mode=S_IFREG|0644, st_size=6159, ...}) = 0
stat("/usr/lib/python2.7/site-packages/tendrl/commons/etcdobj/__init__.py", {st_mode=S_IFREG|0644, st_size=8714, ...}) = 0
stat("/usr/lib/python2.7/site-packages/tendrl/commons/etcdobj/__init__.py", {st_mode=S_IFREG|0644, st_size=8714, ...}) = 0
stat("/usr/lib/python2.7/site-packages/tendrl/commons/objects/__init__.py", {st_mode=S_IFREG|0644, st_size=7108, ...}) = 0
stat("/usr/lib/python2.7/site-packages/tendrl/commons/objects/__init__.py", {st_mode=S_IFREG|0644, st_size=7108, ...}) = 0
stat("/usr/lib/python2.7/site-packages/tendrl/commons/jobs/__init__.py", {st_mode=S_IFREG|0644, st_size=6243, ...}) = 0
stat("/usr/lib/python2.7/site-packages/tendrl/commons/jobs/__init__.py", {st_mode=S_IFREG|0644, st_size=6243, ...}) = 0
stat("/usr/lib64/python2.7/site-packages/gevent/greenlet.py", {st_mode=S_IFREG|0644, st_size=15658, ...}) = 0
stat("/usr/lib64/python2.7/site-packages/gevent/greenlet.py", {st_mode=S_IFREG|0644, st_size=15658, ...}) = 0
stat("/usr/lib/python2.7/site-packages/tendrl/commons/etcdobj/__init__.py", {st_mode=S_IFREG|0644, st_size=8714, ...}) = 0
stat("/usr/lib/python2.7/site-packages/tendrl/commons/etcdobj/__init__.py", {st_mode=S_IFREG|0644, st_size=8714, ...}) = 0
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=118, ...}) = 0
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=118, ...}) = 0
read(9, "\n{\"changed\": true, \"end\": \"2017-"..., 1024) = 456
read(12, "", 1024)                      = 0
close(12)                               = 0
epoll_ctl(4, EPOLL_CTL_ADD, 6, {EPOLLIN, {u32=6, u64=12884901894}}) = -1 EEXIST (File exists)
epoll_ctl(4, EPOLL_CTL_ADD, 9, {EPOLLIN, {u32=9, u64=51719996178441}}) = -1 EEXIST (File exists)
epoll_wait(4, {{EPOLLHUP, {u32=9, u64=51715701211145}}}, 64, 1) = 1
epoll_ctl(4, EPOLL_CTL_MOD, 9, {EPOLLIN, {u32=9, u64=51715701211145}}) = 0
**sendto(6, "GET /v2/keys/queue/4d2fcc2f-19e8"..., 133, 0, NULL, 0) = 133**
fcntl(6, F_GETFL)                       = 0x802 (flags O_RDWR|O_NONBLOCK)
fcntl(6, F_SETFL, O_RDWR|O_NONBLOCK)    = 0
recvfrom(6, "HTTP/1.1 200 OK\r\nContent-Type: a"..., 8192, 0, NULL, NULL) = 351
open("/dev/urandom", O_RDONLY|O_CLOEXEC) = 11
fcntl(11, F_GETFD)                      = 0x1 (flags FD_CLOEXEC)
fcntl(11, F_SETFD, FD_CLOEXEC)          = 0
getuid()                                = 0
getppid()                               = 1
read(11, "Q2\225\363\241\254a\v\310\252\266zx\202\0249", 16) = 16
close(11)                               = 0

**Comment by japplewhite** [comment]
@r0h4n @mkudlej 
I'm seeing this again today: It seems to have been caused by rebooting the Tendrl node when gluster nodes were attached to it. They appear to not have recovered their connections easily


this time strace on the node-agent pid shows..
write(1, "Starting new HTTP connection (1)"..., 41) = 41
sendto(7, "<174>Starting new HTTP connectio"..., 46, 0, NULL, 0) = 46
write(1, "Starting new HTTP connection (1)"..., 41) = 41
sendto(7, "<174>Starting new HTTP connectio"..., 46, 0, NULL, 0) = 46
write(1, "Starting new HTTP connection (1)"..., 41) = 41
sendto(7, "<174>Starting new HTTP connectio"..., 46, 0, NULL, 0) = 46
write(1, "Starting new HTTP connection (1)"..., 41) = 41
sendto(7, "<174>Starting new HTTP connectio"..., 46, 0, NULL, 0) = 46
write(1, "Starting new HTTP connection (1)"..., 41) = 41
sendto(7, "<174>Starting new HTTP connectio"..., 46, 0, NULL, 0) = 46
write(1, "Starting new HTTP connection (1)"..., 41) = 41
sendto(7, "<174>Starting new HTTP connectio"..., 46, 0, NULL, 0) = 46
write(1, "Starting new HTTP connection (1)"..., 41) = 41
sendto(7, "<174>Starting new HTTP connectio"..., 46, 0, NULL, 0) = 46
brk(0)                                  = 0x89d9000
brk(0x89fc000)                          = 0x89fc000
write(1, "Starting new HTTP connection (1)"..., 41) = 41
sendto(7, "<174>Starting new HTTP connectio"..., 46, 0, NULL, 0) = 46
write(1, "Starting new HTTP connection (1)"..., 41) = 41
sendto(7, "<174>Starting new HTTP connectio"..., 46, 0, NULL, 0) = 46
write(1, "Starting new HTTP connection (1)"..., 41) = 41
sendto(7, "<174>Starting new HTTP connectio"..., 46, 0, NULL, 0) = 46
write(1, "Starting new HTTP connection (1)"..., 41) = 41
sendto(7, "<174>Starting new HTTP connectio"..., 46, 0, NULL, 0) = 46
write(1, "Failed to get list of machines f"..., 250) = 250
sendto(7, "<171>Failed to get list of machi"..., 255, 0, NULL, 0) = 255
write(1, "Error connecting to central stor"..., 307) = 307
sendto(7, "<171>Failed to get list of machi"..., 255, 0, NULL, 0) = 255
write(1, "Error connecting to central stor"..., 307^CProcess 1159 detached
 <detached ...>
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 35.08    0.004993          15       338           futex
 32.60    0.004641           9       539           write
 32.24    0.004590           9       534           sendto
  0.08    0.000011          11         1         1 accept
  0.00    0.000000           0         1           read
  0.00    0.000000           0         2         2 open
  0.00    0.000000           0         2           stat
  0.00    0.000000           0         4           brk
  0.00    0.000000           0        14           epoll_wait
  0.00    0.000000           0         2           epoll_ctl
------ ----------- ----------- --------- --------- ----------------
100.00    0.014235                  1437         3 total

**Comment by r0h4n** [comment]
Please try to reproduce this issue

**Comment by r0h4n** [comment]
Closing this issue,  please file an issue with latest resource consumption data and expectations
