### ISSUE TITLE
Node-agent sync fails and hence all cluster details are not populated

### ISSUE THREAD

**Issue by anmolbabu** [Tendrl/node-agent#398]
node_agent - /usr/lib/python2.7/site-packages/tendrl/node_agent/node_sync/__init__.py:353 - _run - ERROR - node_sync failed: Not a directory : /indexes/tags/detected_cluster - EtcdNotDir: [{u'function': u'run', u'line': 327, u'file': u'/usr/lib64/python2.7/site-packages/gevent/greenlet.py', u'statement': u'result = self._run(*self.args, **self.kwargs)'}, {u'function': u'_run', u'line': 102, u'file': u'/usr/lib/python2.7/site-packages/tendrl/node_agent/node_sync/__init__.py', u'statement': u'NS.etcd_orm.client.write(index_key, json.dumps(_node_ids))'}, {u'function': u'write', u'line': 465, u'file': u'/usr/lib/python2.7/site-packages/etcd/client.py', u'statement': u'response = self.api_execute(path, method, params=params)'}, {u'function': u'wrapper', u'line': 874, u'file': u'/usr/lib/python2.7/site-packages/etcd/client.py', u'statement': u'return self._handle_server_response(response)'}, {u'function': u'_handle_server_response', u'line': 954, u'file': u'/usr/lib/python2.7/site-packages/etcd/client.py', u'statement': u'etcd.EtcdError.handle(r)'}, {u'function': u'handle', u'line': 304, u'file': u'/usr/lib/python2.7/site-packages/etcd/__
init__.py', u'statement': u'raise exc(msg, payload)'}]

[root@dhcpxx-xx ~]# rpm -qa|grep tendrl
tendrl-commons-1.2.3-04_20_2017_05_13_04.noarch
tendrl-gluster-integration-1.2.3-04_20_2017_04_39_21.noarch
tendrl-node-monitoring-1.2.3-04_20_2017_04_25_04.noarch
tendrl-node-agent-1.2.3-04_20_2017_00_01_06.noarch

**Comment by r0h4n** [comment]
Steps to reproduce?

**Comment by anmolbabu** [comment]
A normal import cluster is what I did and I imported it as in https://github.com/Tendrl/node-agent/blob/develop/etc/create_sample_job.py

**Comment by anmolbabu** [comment]
Reopening this as I closed it by mistake

**Comment by GowthamShanmugam** [comment]
I have tested with latest rpm it works fine

**Comment by r0h4n** [comment]
@anmolbabu Is this still valid?

**Comment by anmolbabu** [comment]
I used to see this randomly and it seems no more relevant with latest rpms. I am not sure if this has to do with a specific order of things being done(services being started, which I feel is very less likely) or something else... But anyway I'll close this for now...

**Comment by anmolbabu** [comment]
I also see the following error many times:

{"action":"get","node":{"key":"/messages/events/0866a11c-2838-449c-868a-451d429a619d/payload","dir":true,"nodes":[{"key":"/messages/events/0866a11c-2838-449c-868a-451d429a619d/payload/exception_type","value":"TypeError","modifiedIndex":1472162,"createdIndex":1472162},{"key":"/messages/events/0866a11c-2838-449c-868a-451d429a619d/payload/message","value":"node_sync failed: unsupported operand type(s) for +=: 'NoneType' and 'list'","modifiedIndex":1472163,"createdIndex":1472163},{"key":"/messages/events/0866a11c-2838-449c-868a-451d429a619d/payload/exception_traceback","value":"[{u'function': u'run', u'line': 327, u'file': u'/usr/lib64/python2.7/site-packages/gevent/greenlet.py', u'statement': u'result = self._run(*self.args, **self.kwargs)'}, {u'function': u'_run', u'line': 100, u'file': u'/usr/lib/python2.7/site-packages/tendrl/node_agent/node_sync/__init__.py', u'statement': u'_node_ids += [NS.node_context.node_id]'}]","modifiedIndex":1472164,"createdIndex":1472164},{"key":"/messages/events/0866a11c-2838-449c-868a-451d429a619d/payload/exception","value":"!!python/object/apply:exceptions.TypeError ['unsupported operand type(s) for +=: ''NoneType''\n    and ''list''']\n","modifiedIndex":1472165,"createdIndex":1472165}],"modifiedIndex":1472162,"createdIndex":1472162}}

I am closing this for now

@Tendrl/qe Please raise a bug if you find any of these in /messages/events

**Comment by anmolbabu** [comment]
Apr 27 18:29:08 dhcp43-131 journal: 2017-04-27 12:59:08.817539+00:00 - node_agent - /usr/lib/python2.7/site-packages/tendrl/commons/utils/ansible_module_runner.py:37 - __init__ - ERROR - Module path: /usr/lib/python2.7/site-packages/ansible/modules/core/commands/command.py does not exist

Apr 27 18:29:09 dhcp43-131 tendrl-node-agent: 2017-04-27 12:59:08.946385+00:00 - node_agent - /usr/lib/python2.7/site-packages/tendrl/node_agent/node_sync/__init__.py:356 - _run - ERROR - node_sync failed:  - ValueError: [{u'function': u'run', u'line': 327, u'file': u'/usr/lib64/python2.7/site-packages/gevent/greenlet.py', u'statement': u'result = self._run(*self.args, **self.kwargs)'}, {u'function': u'_run', u'line': 60, u'file': u'/usr/lib/python2.7/site-packages/tendrl/node_agent/node_sync/__init__.py', u'statement': u's = NS.tendrl.objects.Service(service=service)'}, {u'function': u'__init__', u'line': 11, u'file': u'/usr/lib/python2.7/site-packages/tendrl/commons/objects/service/__init__.py', u'statement': u'service_detail = self.get_service_info(service)'}, {u'function': u'get_service_info', u'line': 21, u'file': u'/usr/lib/python2.7/site-packages/tendrl/commons/objects/service/__init__.py', u'statement': u'return {"exists": service.exists(), "running": service.status()}'}, {u'function': u'exists', u'line': 23, u'file': u'/usr/lib/python2.7/site-packages/tendrl/commons/utils/service_status.py', u'statement': u"'LoadState',"}, {u'function': u'_execute_service_command', u'line': 16, u'file': u'/usr/lib/python2.7/site-packages/tendrl/commons/utils/service_status.py', u'statement': u'return command.run()'}, {u'function': u'run', u'line': 41, u'file': u'/usr/lib/python2.7/site-packages/tendrl/commons/utils/cmd_utils.py', u'statement': u'**self.attributes'}, {u'function': u'__init__', u'line': 41, u'file': u'/usr/lib/python2.7/site-packages/tendrl/commons/utils/ansible_module_runner.py', u'statement': u'raise ValueError'}]

**Comment by anmolbabu** [comment]
I downgraded ansible to use the one from https://cbs.centos.org/koji/buildinfo?buildID=15268

and now I see the following failure : {u'6f1ef9c3-a3da-4b62-bd11-04d5dc326a50': {u'publisher': u'node_agent', u'job_id': u'', u'timestamp': u'2017-04-27 13:28:18.610904+00:00', u'caller': {u'function': u'_run', u'line_no': u'209', u'filename': u'/usr/lib/python2.7/site-packages/tendrl/commons/jobs/__init__.py'}, u'updated_at': u'2017-04-27 13:28:18.728814+00:00', u'message_id': u'6f1ef9c3-a3da-4b62-bd11-04d5dc326a50', u'priority': u'error', u'parent_id': u'', u'node_id': u'2471b9b0-1565-4e56-b543-48dc0c410db0', u'cluster_id': u'', u'flow_id': u'', u'payload': {u'exception_type': u'ValueError', u'message': u'Job /queue failure, error:No JSON object could be decoded', u'exception_traceback': u'[{u\'function\': u\'run\', u\'line\': 327, u\'file\': u\'/usr/lib64/python2.7/site-packages/gevent/greenlet.py\', u\'statement\': u\'result = self._run(*self.args, **self.kwargs)\'}, {u\'function\': u\'_run\', u\'line\': 60, u\'file\': u\'/usr/lib/python2.7/site-packages/tendrl/commons/jobs/__init__.py\', u\'statement\': u\'raw_job["payload"] = json.loads(job.payload.decode(\\\'utf-8\\\'))\'}, {u\'function\': u\'loads\', u\'line\': 338, u\'file\': u\'/usr/lib64/python2.7/json/__init__.py\', u\'statement\': u\'return _default_decoder.decode(s)\'}, {u\'function\': u\'decode\', u\'line\': 366, u\'file\': u\'/usr/lib64/python2.7/json/decoder.py\', u\'statement\': u\'obj, end = self.raw_decode(s, idx=_w(s, 0).end())\'}, {u\'function\': u\'raw_decode\', u\'line\': 384, u\'file\': u\'/usr/lib64/python2.7/json/decoder.py\', u\'statement\': u\'raise ValueError("No JSON object could be decoded")\'}]', u'exception': u'!!python/object/apply:exceptions.ValueError [No JSON object could be decoded]\n'}}, u'fb9267f0-9787-4824-aacb-0ca940250710': {u'publisher': u'node_agent', u'job_id': u'', u'timestamp': u'2017-04-27 13:28:18.568378+00:00', u'caller': {u'function': u'_run', u'line_no': u'209', u'filename': u'/usr/lib/python2.7/site-packages/tendrl/commons/jobs/__init__.py'}, u'updated_at': u'2017-04-27 13:28:18.651870+00:00', u'message_id': u'fb9267f0-9787-4824-aacb-0ca940250710', u'priority': u'error', u'parent_id': u'', u'node_id': u'49b43a0b-7055-4a57-bca4-ba57f70e5b86', u'cluster_id': u'', u'flow_id': u'', u'payload': {u'exception_type': u'ValueError', u'message': u'Job /queue failure, error:No JSON object could be decoded', u'exception_traceback': u'[{u\'function\': u\'run\', u\'line\': 327, u\'file\': u\'/usr/lib64/python2.7/site-packages/gevent/greenlet.py\', u\'statement\': u\'result = self._run(*self.args, **self.kwargs)\'}, {u\'function\': u\'_run\', u\'line\': 60, u\'file\': u\'/usr/lib/python2.7/site-packages/tendrl/commons/jobs/__init__.py\', u\'statement\': u\'raw_job["payload"] = json.loads(job.payload.decode(\\\'utf-8\\\'))\'}, {u\'function\': u\'loads\', u\'line\': 338, u\'file\': u\'/usr/lib64/python2.7/json/__init__.py\', u\'statement\': u\'return _default_decoder.decode(s)\'}, {u\'function\': u\'decode\', u\'line\': 366, u\'file\': u\'/usr/lib64/python2.7/json/decoder.py\', u\'statement\': u\'obj, end = self.raw_decode(s, idx=_w(s, 0).end())\'}, {u\'function\': u\'raw_decode\', u\'line\': 384, u\'file\': u\'/usr/lib64/python2.7/json/decoder.py\', u\'statement\': u\'raise ValueError("No JSON object could be decoded")\'}]', u'exception': u'!!python/object/apply:exceptions.ValueError [No JSON object could be decoded]\n'}}}

although the job is marked status: finished

**Comment by anmolbabu** [comment]
I also see:
{"action":"get","node":{"key":"/messages/events/92631b3c-4ed0-4ffb-8ee8-8e945cdcf52a/payload","dir":true,"nodes":[{"key":"/messages/events/92631b3c-4ed0-4ffb-8ee8-8e945cdcf52a/payload/exception_type","value":"KeyError","modifiedIndex":166958,"createdIndex":166958},{"key":"/messages/events/92631b3c-4ed0-4ffb-8ee8-8e945cdcf52a/payload/message","value":"Failed to update sds_discovery","modifiedIndex":166960,"createdIndex":166960},{"key":"/messages/events/92631b3c-4ed0-4ffb-8ee8-8e945cdcf52a/payload/exception_traceback","value":"[{u'function': u'run', u'line': 327, u'file': u'/usr/lib64/python2.7/site-packages/gevent/greenlet.py', u'statement': u'result = self._run(*self.args, **self.kwargs)'}, {u'function': u'_run', u'line': 211, u'file': u'/usr/lib/python2.7/site-packages/tendrl/node_agent/node_sync/__init__.py', u'statement': u'sds_detect.load_and_execute_sds_discovery_plugins()'}, {u'function': u'load_and_execute_sds_discovery_plugins', u'line': 47, u'file': u'/usr/lib/python2.7/site-packages/tendrl/node_agent/node_sync/sds_detect.py', u'statement': u'detected_cluster_tag = \"detected_cluster/%s\" % sds_details[\\'detected_cluster_id\\']'}]","modifiedIndex":166962,"createdIndex":166962},{"key":"/messages/events/92631b3c-4ed0-4ffb-8ee8-8e945cdcf52a/payload/exception","value":"!!python/object/apply:exceptions.KeyError [detected_cluster_id]\n","modifiedIndex":166964,"createdIndex":166964}],"modifiedIndex":166958,"createdIndex":166958}}

**Comment by r0h4n** [comment]
Fixed: https://github.com/Tendrl/node-agent/pull/404

**Comment by anmolbabu** [comment]
I also see this:
{"action":"get","node":{"key":"/messages/events/db0df3f5-5e59-4fc1-a54a-c2ce146bfccc/payload","dir":true,"nodes":[{"key":"/messages/events/db0df3f5-5e59-4fc1-a54a-c2ce146bfccc/payload/exception_type","value":"IndexError","modifiedIndex":416530,"createdIndex":416530},{"key":"/messages/events/db0df3f5-5e59-4fc1-a54a-c2ce146bfccc/payload/message","value":"error","modifiedIndex":416531,"createdIndex":416531},{"key":"/messages/events/db0df3f5-5e59-4fc1-a54a-c2ce146bfccc/payload/exception_traceback","value":"[{u'function': u'run', u'line': 327, u'file': u'/usr/lib64/python2.7/site-packages/gevent/greenlet.py', u'statement': u'result = self._run(*self.args, **self.kwargs)'}, {u'function': u'_run', u'line': 321, u'file': u'/usr/lib/python2.7/site-packages/tendrl/gluster_integration/sds_sync/__init__.py', u'statement': u\"if out_lines[index].split('\\\\t')[2].strip() != 'Connected':\"}]","modifiedIndex":416532,"createdIndex":416532},{"key":"/messages/events/db0df3f5-5e59-4fc1-a54a-c2ce146bfccc/payload/exception","value":"!!python/object/apply:exceptions.IndexError [list index out of range]\n","modifiedIndex":416533,"createdIndex":416533}],"modifiedIndex":416530,"createdIndex":416530}}

**Comment by r0h4n** [comment]
Let me know if these still persist

**Comment by r0h4n** [comment]
File the gluster-integration bug on Tendrl/gluster-integration

**Comment by r0h4n** [comment]
@shtripat ^

**Comment by anmolbabu** [comment]
I see one more issue with 

[root@dhcp43-132 ~]# rpm -qa|grep tendrl
tendrl-commons-1.2.3-05_02_2017_16_12_13.noarch
tendrl-node-monitoring-1.2.3-05_02_2017_04_25_04.noarch
tendrl-node-agent-1.2.3-05_02_2017_16_15_57.noarch
tendrl-gluster-integration-1.2.3-05_02_2017_01_12_04.noarch

which was gone for a while but occured to me again today...

The error is :

{u'publisher': u'node_agent', u'job_id': u'', u'timestamp': u'2017-05-02 15:05:59.348072+00:00', u'caller': {u'function': u'_run', u'line_no': u'356', u'filename': u'/usr/lib/python2.7/site-packages/tendrl/node_agent/node_sync/__init__.py'}, u'updated_at': u'2017-05-02 15:05:59.459402+00:00', u'payload': {u'exception_type': u'EtcdNotFile', u'message': u'node_sync failed: Not a file : /indexes/tags/detected_cluster', u'exception_traceback': u"[{u'function': u'run', u'line': 327, u'file': u'/usr/lib64/python2.7/site-packages/gevent/greenlet.py', u'statement': u'result = self._run(*self.args, **self.kwargs)'}, {u'function': u'_run', u'line': 105, u'file': u'/usr/lib/python2.7/site-packages/tendrl/node_agent/node_sync/__init__.py', u'statement': u'NS.etcd_orm.client.write(index_key, json.dumps(_node_ids))'}, {u'function': u'write', u'line': 465, u'file': u'/usr/lib/python2.7/site-packages/etcd/client.py', u'statement': u'response = self.api_execute(path, method, params=params)'}, {u'function': u'wrapper', u'line': 874, u'file': u'/usr/lib/python2.7/site-packages/etcd/client.py', u'statement': u'return self._handle_server_response(response)'}, {u'function': u'_handle_server_response', u'line': 954, u'file': u'/usr/lib/python2.7/site-packages/etcd/client.py', u'statement': u'etcd.EtcdError.handle(r)'}, {u'function': u'handle', u'line': 304, u'file': u'/usr/lib/python2.7/site-packages/etcd/__init__.py', u'statement': u'raise exc(msg, payload)'}]", u'exception': u"!!python/object/apply:etcd.EtcdNotFile\nargs: ['Not a file : /indexes/tags/detected_cluster']\nstate:\n  payload: {!!python/unicode 'cause': !!python/unicode '/indexes/tags/detected_cluster',\n    !!python/unicode 'errorCode': 102, !!python/unicode 'index': 23173, !!python/unicode 'message': !!python/unicode 'Not\n      a file', status: 403}\n"}, u'priority': u'error', u'parent_id': u'', u'node_id': u'3b9af815-e014-4ae2-8941-4d33dafcbf61', u'cluster_id': u'', u'flow_id': u'', u'message_id': u'88823e5a-4f95-4d01-88cd-97b654653dec'}

**Comment by GowthamShanmugam** [comment]
i am also seeing this error

**Comment by GowthamShanmugam** [comment]
i have checked key is coming 
  /indexes/tags/detected_cluster/ee504ea39597a397d7ca23a1c25b2a7f64e13e6a1e8bf80a3cfd7d7dbabddb3f

but in etcd /indexes/tags/detected_cluster we have to store under this key only

**Comment by GowthamShanmugam** [comment]
node context tags 
{
key: "/nodes/47f0e02e-d9a7-4d46-8c02-1492b5250046/NodeContext/tags",
value: "["detected_cluster/e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855", "detected_cluster/", "gluster/server", "tendrl/node"]",
modifiedIndex: 27968,
createdIndex: 27968
},

detected_cluster tag coming twice

**Comment by GowthamShanmugam** [comment]
problem is some times detected cluster id is populated in little bit late after creating detected cluster directory
