### ISSUE TITLE
Etcd is overloaded with /messages/events 

### ISSUE THREAD

**Issue by mkudlej** [Tendrl/node-agent#403]
after few days I have in Etcd in /messages/events more than 80000 records which overload Etcd. To be more specific Etcd uses because of this RSS = 7GB. I see that there are jus duplicates of couple of events. I think this issue is related to https://github.com/Tendrl/specifications/issues/86

**Comment by r0h4n** [comment]
Please make use of this config flag to set TTL for /messages 

https://github.com/Tendrl/node-agent/blob/develop/etc/tendrl/node-agent/node-agent.conf.yaml.sample#L8

**Comment by r0h4n** [comment]
I would recommend using a value which ~= 24 hrs
