### ISSUE TITLE
Don't require system directories to run from source, set defaults and accept environment variables for path configuration.

### ISSUE THREAD

**Issue by brainfunked** [Tendrl/node-agent#41]
This issue builds on https://github.com/Tendrl/common/issues/60 and https://github.com/Tendrl/common/issues/62.

Currently, system directories such as `/etc/tendrl`, `/var/log/tendrl` are required for node agent to be installed and run from source. Any source based installation must be able to run without requiring any directories or files to be present system-wide. This is to ensure that a user not require root privileges on the system to be able to run the node agent. The following proposed changes all assume that the top level directory is the checkout of the node_agent git repository at `~/git/node_agent`.

1. Ship a default configuration file under `etc/node_agent_logging.yaml`. This file should log to the directory addressed via relative path eg. `log/node_agent_info.log`. This would result in the log files being created in `~/git/node_agent/log`. As stated in https://github.com/Tendrl/common/issues/62, there should not be a separate need to configure any kind of logging for the common library.
2. Hardcode the use of the above node agent specific configuration file in the code, as the default eg. `/var/log/tendrl/node_agent.log`.
3. Allow environment variables to override the hardcoded configuration file path.
4. Ship sample configuration files that contain system-wide deployment paths.
5. Installation instructions (and rpm package spec files) would explicitly point towards the system-wide deployment sample configuration files and use the environment variables to override these at node agent startup.

**Comment by r0h4n** [comment]
Developments after this bug now require the tendrl-node-agent to be invoked with root privileges, closing this one for now
