### ISSUE TITLE
Node properties are not getting synced sometimes

### ISSUE THREAD

**Issue by gnehapk** [Tendrl/node-agent#414]
In the GetNodeList API call, sometimes the "disks", "disks.free" and "disks.used" properties are missing in the GetNodeList API response.

@nthomas-redhat @brainfunked @shtripat @GowthamShanmugam @sankarshanmukhopadhyay @anivargi @r0h4n

**Comment by GowthamShanmugam** [comment]
@r0h4n we can close this, this issue is fixed
