### ISSUE TITLE
import job passed even if subjob failed

### ISSUE THREAD

**Issue by mkudlej** [Tendrl/node-agent#422]
Please look at screenshot 

![tendrl_bug](https://cloud.githubusercontent.com/assets/5920442/25894073/c468cb82-357a-11e7-9224-131b51f26fb5.png)

Same error I see on one of node-agent nodes:
```
...
node_agent - /usr/lib/python2.7/site-packages/tendrl/commons/flows/create_cluster/utils.py:134 - gluster_create_ssh_setup_jobs - ERROR - aa44a61b-bfe7-4a89-8515-232e81d92f61:Error adding authorized key
node_agent - /usr/lib/python2.7/site-packages/tendrl/commons/flows/import_cluster/__init__.py:113 - run - INFO - aa44a61b-bfe7-4a89-8515-232e81d92f61:SSH setup completed for all nodes in cluster 32600bc2-42a6-4745-a048-c476e317a598
May 10 08:42:40 dahorak-usm1-gl2 tendrl-node-agent: 2017-05-10 08:42:40.195181+00:00 - commons - /usr/lib/python2.7/site-packages/tendrl/commons/utils/ssh/authorize_key.py:74 - run - WARNING - Unable to copy authorize key .err:ValueError('No JSON object could be decoded',)
...
```

I think that any job *should failed* if sub-job fails.

**Comment by mbukatov** [comment]
I have few additional question related to this problem:

* How would I get more information for the error reported there?
* Why the task went on no matter that adding key failed? Did it affect the result of the task? How would I know based on the task details shown in the screenshot?
* Should the error affect the state of the task?

**Comment by nnDarshan** [comment]
@mbukatov
- Events would have more information about the failure.
- The import cluster should have failed once it encountered this issue. Its a bug, have posted a fix for it. The implication is, without successful authorized key copy, further CRUD operations on the cluster would be affected. 
Eg. you wont be able to create a volume on this cluster. 
So if this step fails, it should consider the whole import task as failed

**Comment by mbukatov** [comment]
@nnDarshan Ok, thanks for the details.

**Comment by r0h4n** [comment]
@mkudlej This issue has been fixed, please try to reproduce the issue

**Comment by mkudlej** [comment]
@r0h4n Fix  https://github.com/nnDarshan/bridge_common/commit/40953ff739dcdefac2c4422faf92734838ebd04a is just about fixing that particular error.
But my first comment was more about that **if sub-job fails then job should fail**. I would like to avoid user misinterpretation of job *pass* like here https://bugzilla.redhat.com/show_bug.cgi?id=1333399.

**Comment by r0h4n** [comment]
@mkudlej If sub-job fails then job will fail, we have made appropriate changes in this file 

https://github.com/Tendrl/commons/blob/develop/tendrl/commons/jobs/__init__.py#L292

Can you reproduce this issue?

**Comment by mkudlej** [comment]
Reproduces with:
```
#server
ceph-ansible-2.2.0-100.g0a51552.el7.noarch
ceph-installer-1.3.0-7.g9289910.el7.noarch
etcd-3.1.3-1.el7.x86_64
python-etcd-0.4.5-1.noarch
rubygem-etcd-0.3.0-1.el7.centos.noarch
tendrl-api-1.2.3-05_12_2017_01_51_04.noarch
tendrl-api-doc-1.2.3-05_12_2017_01_51_04.noarch
tendrl-api-httpd-1.2.3-05_12_2017_01_51_04.noarch
tendrl-commons-1.2.3-05_12_2017_05_24_17.noarch
tendrl-dashboard-1.2.3-05_12_2017_04_11_04.noarch
tendrl-node-agent-1.2.3-05_12_2017_00_01_05.noarch
tendrl-performance-monitoring-1.2.3-05_12_2017_03_02_05.noarch
```
and
```
#storage node
glusterfs-3.9.1-1.el7.x86_64
glusterfs-api-3.9.1-1.el7.x86_64
glusterfs-api-devel-3.9.1-1.el7.x86_64
glusterfs-cli-3.9.1-1.el7.x86_64
glusterfs-client-xlators-3.9.1-1.el7.x86_64
glusterfs-devel-3.9.1-1.el7.x86_64
glusterfs-events-3.9.1-1.el7.x86_64
glusterfs-extra-xlators-3.9.1-1.el7.x86_64
glusterfs-fuse-3.9.1-1.el7.x86_64
glusterfs-geo-replication-3.9.1-1.el7.x86_64
glusterfs-libs-3.9.1-1.el7.x86_64
glusterfs-rdma-3.9.1-1.el7.x86_64
glusterfs-server-3.9.1-1.el7.x86_64
python-etcd-0.4.5-1.noarch
python-gluster-3.9.1-1.el7.noarch
tendrl-commons-1.2.3-05_12_2017_05_24_17.noarch
tendrl-gluster-integration-1.2.3-05_12_2017_04_39_17.noarch
tendrl-node-agent-1.2.3-05_12_2017_00_01_05.noarch
tendrl-node-monitoring-1.2.3-05_12_2017_04_25_05.noarch
```
![tendrl_bug2](https://cloud.githubusercontent.com/assets/5920442/25994850/e8cfdb1e-370f-11e7-9af4-cc5fb8ae5034.png)

As you can see job has passed but sub-job failed.

**Comment by r0h4n** [comment]
@nnDarshan Please check this out

**Comment by r0h4n** [comment]
This is fixed in (Tendrl/commons:develop) and will packaged downstream soon
