### ISSUE TITLE
Import of Gluster cluster is not possible if cluster is created after node-agent installation

### ISSUE THREAD

**Issue by mbukatov** [Tendrl/node-agent#467]
When you install install and configure tendrl-node-agent on Storage Nodes during Tendrl installation, and then create ~Ceph~ Gluster (edited based on https://github.com/Tendrl/node-agent/issues/467#issuecomment-306691174) cluster outside of Tendrl (eg. because you require special setup, which Tendrl doesn't support yet), Tendrl is not able to import the cluster.

While this problem has been identified as a root cause of https://github.com/Tendrl/node-agent/issues/435, which is now closed, but since such behavior seems like a design mistake to me, clarification with broader audience is needed.

## Additional information

QE team has a temporary workaround for this (which rules out some valid use cases) here: https://github.com/Tendrl/usmqe-setup/pull/99 - tracked by https://github.com/Tendrl/usmqe-setup/issues/100

**Comment by r0h4n** [comment]
IMO, this should be addressed with a lower priority.

Till then, I think it is reasonable to install the ceph cluster before installing tendrl components. Sounds good?

**Comment by mbukatov** [comment]
While I agree that it's not a big issue at this point (it's not a test blocker and simple workaround exists), I'm not sure how big problem this would be for real use cases and for this reason, I would like to get an agreement on a priority of this issue, so that we are able to fix it in reasonable time if needed.

@japplewhite Thoughts?

**Comment by japplewhite** [comment]
@mbukatov I would classify this as a GA blocker. We need to make sure upstream docs call this out as a known issue for import until then. Do we have a known issues list?

**Comment by r0h4n** [comment]
Folks, I didnt dig deep into this issue when I last responded, but this scenario is already handled by Tendrl.

@mbukatov can you provide us detailed steps or show us how you encounter this bug on a call? 

The tendrl-node-agents keep discovering ceph/gluster service after a regular interval, and based on the state of the cluster, tendrl-node-agent creates the DetectedCluster object in /nodes/:node_id/DetectedCluster

**Comment by mbukatov** [comment]
@r0h4n I wouldn't be able to check that this week, but you are right, [the workaround](https://github.com/Tendrl/usmqe-setup/pull/99) introduced by @fbalak based on @dahorak conversation with you is affecting gluster mostly, I'm updating the description of the issue. But the good thing is that we started to clarify the expectations here, which is the main reason I created this issue.

**Comment by r0h4n** [comment]
@mbukatov any updates?

**Comment by mbukatov** [comment]
@r0h4n I tried to create trusted storage pool after installing tendrl (latest upstream release, eg. tendrl-commons-1.4.1-2): it was possible to initiate import from Tendrl web and the task finished.

I will check with @fbalak next week to verify that I understand the original issue right and if so, we can declare this as fixed.

**Comment by mbukatov** [comment]
I'm closing this - @fbalak is you disagree, open it again.

**Comment by fbalak** [comment]
@mbukatov ok

**Comment by mbukatov** [comment]
@mkudlej sees this again with [v1.5.0](https://github.com/Tendrl/documentation/wiki/Tendrl-release-v1.5.0-(summary))

**Comment by mkudlej** [comment]
I've tried to install v1.5.0 and unfortunately I've missed note in https://github.com/Tendrl/documentation/wiki/Tendrl-release-v1.5.0-(install-doc) that Gluster should be peer probed before tendrl-node-agent installation. I've installed Tendrl packages before Gluster. There should be note at beginning of storage installation section that Gluster should be installed before start of Tendrl installation.
I've tried to restart storage nodes, reinstall tendrl-node-package.

**Comment by r0h4n** [comment]
I have updated the document https://github.com/Tendrl/documentation/wiki/Tendrl-Package-Installation-Reference(Revised)   (section: "Storage Node Installation")  so as to make the already documented pre-requisite more obvious.

Before Tendrl imports the gluster cluster:
- Tendrl manages existing Gluster clusters, which means you have to install Gluster before any Tendrl services are even started.
- Tendrl (and Gluster itself) requires and probes for an Trusted storage pool https://gluster.readthedocs.io/en/latest/Administrator%20Guide/Storage%20Pools/  to even function.
- Tendrl checks "gluster pool list" and groups together all the nodes in the pool list as a importable cluster.

After Tendrl imports the gluster cluster:
- If user wants add nodes to the Trusted storage pool, he has to invoke Tendrl ExpandCluster API (which is being planned and not in place yet).

Marking this issue as invalid , but if you still have confusions, please post here

**Comment by mbukatov** [comment]
@mkudlej

**Comment by r0h4n** [comment]
This has been addressed, you can now install some/all Gluster nodes after installing Tendrl agents, although this is not advised by the Tendrl team and your results may vary
