### ISSUE TITLE
Update name of tendrl-api service

### ISSUE THREAD

**Issue by mbukatov** [Tendrl/node-agent#485]
Since the [name of tendrl-api service has been recently updated](https://github.com/Tendrl/api/issues/45), list `TENDRL_SERVICES` in `tendrl/node_agent/node_sync/__init__.py`  should be updated as well and contain `tendrl-api` instead of `tendrl-apid`.

**Comment by r0h4n** [comment]
Thanks for pointing this one, we shouldnt have missed this part

Fixed: https://github.com/Tendrl/node-agent/commit/efbe3ef5fa4f8723f4dd52dd5ba8a3c1f7f0b131

**Comment by mbukatov** [comment]
Based on the search results in all tendrl repositories, I created two other similar issues.
