### ISSUE TITLE
Mark Disk with ssd flag

### ISSUE THREAD

**Issue by r0h4n** [Tendrl/node-agent#489]
Current:
- Tendrl finds an ssd via the lsblk command, during which it assigns all BlockDevices with the ssd flag

Expectation:
- Tendrl should also mark the raw Disk (backing the block devices) with the ssd flag

**Comment by r0h4n** [comment]
@anivargi @cloudbehl @brainfunked @GowthamShanmugam Now along with BlockDevices,

Disks will also contain the ssd flag.

@brainfunked I have not removed the ssd flag from blockdevices because that would break the current api and ui.

**Comment by brainfunked** [comment]
@r0h4n Yeah. Since the flag is made available on the block device by the system, we should also maintain it on the BlockDevice object.
