### ISSUE TITLE
Gluster trusted pool create job fails with "No module named python_gdeploy.actions.install_gluster"

### ISSUE THREAD

**Issue by japplewhite** [Tendrl/node-agent#494]
Installation was attempted on virtualbox, 4 storage nodes, two disks each using a SATA Controller (similar to the Ceph-deploy vagrant environment).

full log here:
info Processing Job 91b25b5a-4b36-45b6-9b0e-32205e902afe 08 Jun 2017 04:33:58
info Running Flow tendrl.flows.CreateCluster 08 Jun 2017 04:33:58
warning Mandatory parameter Cluster.public_network not provided 08 Jun 2017 04:33:58
warning Mandatory parameter Cluster.conf_overrides not provided 08 Jun 2017 04:33:58
info Created SSH setup job 55040d65-6b32-4481-82cb-6fcea72fb952 for node 8e0a6ffe-e82d-4cc0-8960-75b2b274f6a3 08 Jun 2017 04:34:18
info Created SSH setup job 8d5c2264-4335-419e-aa6a-977a8c2da8cf for node adbd9f54-0f2e-4d04-bd90-8898ad53cda9 08 Jun 2017 04:34:20
info Created SSH setup job d56ac6da-3238-47fc-9771-11b72c155a55 for node c325f12b-bf41-43a2-9445-376a65d8cc66 08 Jun 2017 04:34:22
info Processing Job d56ac6da-3238-47fc-9771-11b72c155a55 08 Jun 2017 04:38:04
info Running Flow tendrl.flows.AuthorizeSshKey 08 Jun 2017 04:38:05
info Job (d56ac6da-3238-47fc-9771-11b72c155a55): Finished Flow tendrl.flows.AuthorizeSshKey 08 Jun 2017 04:38:05
info Processing Job 55040d65-6b32-4481-82cb-6fcea72fb952 08 Jun 2017 04:38:39
info Running Flow tendrl.flows.AuthorizeSshKey 08 Jun 2017 04:38:39
info Job (55040d65-6b32-4481-82cb-6fcea72fb952): Finished Flow tendrl.flows.AuthorizeSshKey 08 Jun 2017 04:38:39
info Processing Job 8d5c2264-4335-419e-aa6a-977a8c2da8cf 08 Jun 2017 04:38:51
info Running Flow tendrl.flows.AuthorizeSshKey 08 Jun 2017 04:38:51
info Job (8d5c2264-4335-419e-aa6a-977a8c2da8cf): Finished Flow tendrl.flows.AuthorizeSshKey 08 Jun 2017 04:38:52
info SSH setup completed for all nodes in cluster 6b52674f-25cf-44c1-b929-df032243d8a7 08 Jun 2017 04:38:54
info Starting SDS install and config 6b52674f-25cf-44c1-b929-df032243d8a7 08 Jun 2017 04:38:55
info Creating Gluster Storage Cluster 6b52674f-25cf-44c1-b929-df032243d8a7 08 Jun 2017 04:38:55
info Setting up gluster nodes 6b52674f-25cf-44c1-b929-df032243d8a7 08 Jun 2017 04:38:55
error Job failed No module named python_gdeploy.actions.install_gluster: No module named python_gdeploy.actions.install_gluster 08 Jun 2017 04:38:56

**Comment by japplewhite** [comment]
Possibly related error in logs:
Jun  7 15:58:56 localhost tendrl-node-agent: 2017-06-07 15:58:47.342593+00:00 - performance_monitoring - /usr/lib/python2.7/site-packages/tendrl/performance_monitoring/aggregator/node_summary.py:234 - calculate_host_summary - ERROR - Exception caught while trying to save summary for node c325f12b-bf41-43a2-9445-376a65d8cc66 - EtcdKeyNotFound: [{u'function': u'run', u'line': 327, u'file': u'/usr/lib64/python2.7/site-packages/gevent/greenlet.py', u'statement': u'result = self._run(*self.args, **self.kwargs)'}, {u'function': u'_run', u'line': 262, u'file': u'/usr/lib/python2.7/site-packages/tendrl/performance_monitoring/aggregator/node_summary.py', u'statement': u'self.calculate_host_summaries()'}, {u'function': u'calculate_host_summaries', u'line': 258, u'file': u'/usr/lib/python2.7/site-packages/tendrl/performance_monitoring/aggregator/node_summary.py', u'statement': u'self.calculate_host_summary(node)'}, {u'function': u'calculate_host_summary', u'line': 221, u'file': u'/usr/lib/python2.7/site-packages/tendrl/performance_monitoring/aggregator/node_summary.py', u'statement': u'node'}, {u'function': u'get_node_selinux_mode', u'line': 356, u'file': u'/usr/lib/python2.7/site-packages/tendrl/performance_monitoring/utils/central_store_util.py', u'statement': u"'nodes/%s/Os/selinux_mode' % node_id"}, {u'function': u'read', u'line': 597, u'file': u'/usr/lib/python2.7/site-packages/etcd/client.py', u'statement': u'timeout=timeout)'}, {u'function': u'wrapper', u'line': 907, u'file': u'/usr/lib/python2.7/site-packages/etcd/client.py', u'statement': u'return self._handle_server_response(response)'}, {u'function': u'_handle_server_response', u'line': 987, u'file': u'/usr/lib/python2.7/site-packages/etcd/client.py', u'statement': u'etcd.EtcdError.handle(r)'}, {u'function': u'handle', u'line': 306, u'file': u'/usr/lib/python2.7/site-packages/etcd/__init__.py', u'statement': u'raise exc(msg, payload)'}]

**Comment by shtripat** [comment]
@japplewhite in case of gluster cluster creation, one of the storage nodes should have tag `provisioner/gluster` and `gdeploy` repository should be configured on this node. Looks like same thing is not done here and that's why `gdeploy` in not installed on provisioner node and not found while runtime.

Kindly verify this.

**Comment by nnDarshan** [comment]
@japplewhite The node where user has marked as "provisioner/gluster", he needs to configured this [1] repo. During cluster creation, gdeploy will be installed on that machine. 

Could you please check if repo is configured on "provisioner/gluster"

[1] https://copr.fedorainfracloud.org/coprs/sac/gdeploy/repo/epel-7/sac-gdeploy-epel-7.repo

**Comment by r0h4n** [comment]
I am closing this one, please follow instructions as given here https://github.com/Tendrl/node-agent/issues/494#issuecomment-307292325
