### ISSUE TITLE
Node discovery fails in VirtualBox

### ISSUE THREAD

**Issue by japplewhite** [Tendrl/node-agent#504]
Nodes do not show up as usable in virtualbox. 

Node info on disks.
[root@stg01 ~]# hwinfo --disk
11: IDE 00.0: 10600 Disk
  [Created at block.245]
  Unique ID: 3OOL.cMlqCJOAtQ5
  Parent ID: mnDB.V_9AHXukieF
  SysFS ID: /class/block/sda
  SysFS BusID: 0:0:0:0
  SysFS Device Link: /devices/pci0000:00/0000:00:01.1/ata1/host0/target0:0:0/0:0:0:0
  Hardware Class: disk
  Model: "VBOX HARDDISK"
  Vendor: "VBOX"
  Device: "HARDDISK"
  Revision: "1.0"
  Serial ID: "VB1ac949fd-46e0836d"
  Driver: "ata_piix", "sd"
  Driver Modules: "ata_piix"
  Device File: /dev/sda
  Device Files: /dev/sda, /dev/disk/by-id/ata-VBOX_HARDDISK_VB1ac949fd-46e0836d, /dev/disk/by-path/pci-0000:00:01.1-ata-1.0
  Device Number: block 8:0-8:15
  BIOS id: 0x80
  Geometry (Logical): CHS 5221/255/63
  Size: 83886080 sectors a 512 bytes
  Capacity: 40 GB (42949672960 bytes)
  Geometry (BIOS EDD): CHS 83220/16/63
  Size (BIOS EDD): 83886080 sectors
  Geometry (BIOS Legacy): CHS 1024/255/63
  Config Status: cfg=new, avail=yes, need=no, active=unknown
  Attached to: #4 (IDE interface)

12: IDE 01.0: 10600 Disk
  [Created at block.245]
  Unique ID: WZeP.1q2gg+vKQuF
  Parent ID: mnDB.V_9AHXukieF
  SysFS ID: /class/block/sdb
  SysFS BusID: 0:0:1:0
  SysFS Device Link: /devices/pci0000:00/0000:00:01.1/ata1/host0/target0:0:1/0:0:1:0
  Hardware Class: disk
  Model: "VBOX HARDDISK"
  Vendor: "VBOX"
  Device: "HARDDISK"
  Revision: "1.0"
  Serial ID: "VBecb16747-d60caba0"
  Driver: "ata_piix", "sd"
  Driver Modules: "ata_piix"
  Device File: /dev/sdb
  Device Files: /dev/sdb, /dev/disk/by-id/ata-VBOX_HARDDISK_VBecb16747-d60caba0, /dev/disk/by-path/pci-0000:00:01.1-ata-1.1
  Device Number: block 8:16-8:31
  Geometry (Logical): CHS 1402/255/63
  Size: 22528000 sectors a 512 bytes
  Capacity: 10 GB (11534336000 bytes)
  Config Status: cfg=new, avail=yes, need=no, active=unknown
  Attached to: #4 (IDE interface)

13: IDE 100.0: 10600 Disk
  [Created at block.245]
  Unique ID: _kuT.QTGyYTXApo1
  Parent ID: mnDB.V_9AHXukieF
  SysFS ID: /class/block/sdc
  SysFS BusID: 1:0:0:0
  SysFS Device Link: /devices/pci0000:00/0000:00:01.1/ata2/host1/target1:0:0/1:0:0:0
  Hardware Class: disk
  Model: "VBOX HARDDISK"
  Vendor: "VBOX"
  Device: "HARDDISK"
  Revision: "1.0"
  Serial ID: "VB42405663-a6ae3b67"
  Driver: "ata_piix", "sd"
  Driver Modules: "ata_piix"
  Device File: /dev/sdc
  Device Files: /dev/sdc, /dev/disk/by-id/ata-VBOX_HARDDISK_VB42405663-a6ae3b67, /dev/disk/by-path/pci-0000:00:01.1-ata-2.0
  Device Number: block 8:32-8:47
  Geometry (Logical): CHS 1402/255/63
  Size: 22528000 sectors a 512 bytes
  Capacity: 10 GB (11534336000 bytes)
  Config Status: cfg=new, avail=yes, need=no, active=unknown
  Attached to: #4 (IDE interface)

**Comment by r0h4n** [comment]
@GowthamShanmugam please take a look at this

**Comment by GowthamShanmugam** [comment]
Working on

**Comment by GowthamShanmugam** [comment]
I have tested this in virtual box it works fine, i have created one server and one node in virtual box, i have added two disk for nodes in virtualbox then i have started node-agent all free disk are displayed in UI
