### ISSUE TITLE
Adds sync_status, last_sync attributes to node context and cluster node context

### ISSUE THREAD

**Issue by r0h4n** [Tendrl/node-agent#505]
tendrl-node-agents should set attributes `sync_status` and `last_sync` for node_context and cluster_node_context during node sync

valid vaules for `sync_status` will be "in_progress" , "done", "failed"

`last_sync` is the UTC time datetime of the last sync completion

**Comment by brainfunked** [comment]
In a scenario where the sync succeeds partially, we need to set an alert condition on the node but the sync status should be done.
