### ISSUE TITLE
Node agent crashes with etcd.EtcdAlreadyExist: Key already exists : /indexes/machine_id/5e6d9cd23af6f381decb0d58bd927840

### ISSUE THREAD

**Issue by japplewhite** [Tendrl/node-agent#519]
Brought up a testbed in GCE cloud. Storage nodes had 1 SSD and 1 Rotational disk.
Agent crashed on restart with:

Jun 19 17:50:13 stg01 tendrl-node-monitoring: flows in namespace.tendrl.objects.Service.flowsRegistering object namespace.tendrl.objects.TendrlContextFinding atoms in namespace.tendrl.objects.TendrlContext.atomsFinding flows in namespace.tendrl.objects.TendrlContext.flowsRegistering object namespace.tendrl.objects.DiskFinding atoms in namespace.tendrl.objects.Disk.atomsFinding flows in namespace.tendrl.objects.Disk.flowsRegistering object namespace.tendrl.objects.VirtualDiskFinding atoms in namespace.tendrl.objects.VirtualDisk.atomsFinding flows in namespace.tendrl.objects.VirtualDisk.flowsFinding flows in namespace.tendrl.flowsRegistering flow namespace.tendrl.flows.AuthorizeSshKeyRegistering flow namespace.tendrl.flows.CreateClusterRegistering flow namespace.tendrl.flows.ExpandClusterRegistering flow namespace.tendrl.flows.ImportClusterRegistering flow namespace.tendrl.flows.SetupSshSetup Tendrl definitions (.yml)for namespace.tendrlValidating registered (.py) flows in namespace.tendrl.flowsValidating defined (.yml) flows in namespace.tendrl.flowsValidating registered (.py) objects in namespace.tendrl.objectsValidating defined (.yml) objects in namespace.tendrl.objectsSetup NodeContext for namespace.tendrlLoad definitions (.yml) for namespace.tendrl.objects.NodeContextTraceback (most recent call last):
Jun 19 17:50:13 stg01 tendrl-node-monitoring: File "/usr/bin/tendrl-node-monitoring", line 9, in 
Jun 19 17:50:13 stg01 tendrl-node-monitoring: load_entry_point('tendrl-node-monitoring==1.4.2', 'console_scripts', 'tendrl-node-monitoring')()
Jun 19 17:50:13 stg01 tendrl-node-monitoring: File "/usr/lib/python2.7/site-packages/tendrl/node_monitoring/manager/init.py", line 24, in main
Jun 19 17:50:13 stg01 tendrl-node-monitoring: TendrlNS()
Jun 19 17:50:13 stg01 tendrl-node-monitoring: File "/usr/lib/python2.7/site-packages/tendrl/commons/init.py", line 44, in init
Jun 19 17:50:13 stg01 tendrl-node-monitoring: self.setup_common_objects()
Jun 19 17:50:13 stg01 tendrl-node-monitoring: File "/usr/lib/python2.7/site-packages/tendrl/commons/init.py", line 280, in setup_common_objects
Jun 19 17:50:13 stg01 tendrl-node-monitoring: self.current_ns.objects.NodeContext()
Jun 19 17:50:13 stg01 tendrl-node-monitoring: File "/usr/lib/python2.7/site-packages/tendrl/commons/objects/node_context/init.py", line 28, in init
Jun 19 17:50:13 stg01 tendrl-node-monitoring: self.node_id = node_id or self._get_node_id() or self._create_node_id()
Jun 19 17:50:13 stg01 tendrl-node-monitoring: File "/usr/lib/python2.7/site-packages/tendrl/commons/objects/node_context/init.py", line 73, in _create_node_id
Jun 19 17:50:13 stg01 tendrl-node-monitoring: NS._int.wclient.write(index_key, node_id, prevExist=False)
Jun 19 17:50:13 stg01 tendrl-node-monitoring: File "/usr/lib/python2.7/site-packages/etcd/client.py", line 500, in write
Jun 19 17:50:13 stg01 tendrl-node-monitoring: response = self.api_execute(path, method, params=params)
Jun 19 17:50:13 stg01 tendrl-node-monitoring: File "/usr/lib/python2.7/site-packages/etcd/client.py", line 907, in wrapper
Jun 19 17:50:13 stg01 tendrl-node-monitoring: return self._handle_server_response(response)
Jun 19 17:50:13 stg01 tendrl-node-monitoring: File "/usr/lib/python2.7/site-packages/etcd/client.py", line 987, in _handle_server_response
Jun 19 17:50:13 stg01 tendrl-node-monitoring: etcd.EtcdError.handle(r)
Jun 19 17:50:13 stg01 tendrl-node-monitoring: File "/usr/lib/python2.7/site-packages/etcd/init.py", line 306, in handle
Jun 19 17:50:13 stg01 tendrl-node-monitoring: raise exc(msg, payload)
Jun 19 17:50:13 stg01 tendrl-node-monitoring: etcd.EtcdAlreadyExist: Key already exists : /indexes/machine_id/5e6d9cd23af6f381decb0d58bd927840
Jun 19 17:50:13 stg01 systemd: tendrl-node-monitoring.service: main process exited, code=exited, status=1/FAILURE
Jun 19 17:50:13 stg01 systemd: Unit tendrl-node-monitoring.service entered failed state.
Jun 19 17:50:13 stg01 systemd: tendrl-node-monitoring.service failed.
Jun 19 17:50:13 stg01 systemd: tendrl-node-monitoring.service holdoff time over, scheduling restart.
Jun 19 17:50:13 stg01 systemd: start request repeated too quickly for tendrl-node-monitoring.service
Jun 19 17:50:13 stg01 systemd: Unit tendrl-node-monitoring.service entered failed state.
Jun 19 17:50:13 stg01 systemd: tendrl-node-monitoring.service failed.

**Comment by r0h4n** [comment]
Tendrl node-agents are uniquely identified by a a map {machine_id : tendrl node id} 

Seems like the you have the same machine id for more than one Nodes

**Comment by japplewhite** [comment]
@brainfunked @r0h4n I agree - using machine-id caused us lots of problems in skyrings. people simply aren't aware of the machine-id and it's intended use so it resulted in lots of unintended user problems.

**Comment by r0h4n** [comment]
Ack
https://github.com/Tendrl/node-agent/issues/532

**Comment by mbukatov** [comment]
See https://github.com/Tendrl/tendrl-ansible/issues/12 for additional discussion on this topic.
