### ISSUE TITLE
Add "cluster_alias" attr for object TendrlContext

### ISSUE THREAD

**Issue by r0h4n** [Tendrl/node-agent#520]
Tendrl users should be able to give an alias to their ceph or gluster clusters which is different than the `cluster_name` (which is specific to ceph and gluster).

This new attr `cluster_alias` should be added to the TendrlContext and the existing create/import flows need to add `cluster_alias` as a mandatory input and the API/UI have to provide this input

**Comment by r0h4n** [comment]
@julienlim @japplewhite

**Comment by japplewhite** [comment]
I agree - when we have a cluster config page we can clearly show all the detailed attributes
