### ISSUE TITLE
disk raw_reference is common for virtual and physical disk

### ISSUE THREAD

**Issue by GowthamShanmugam** [Tendrl/node-agent#522]
Now we are storing disk raw reference in /nodes/{node_id}/LocalStorage/Disks/RawReference, but virtual disks also have disk raw_reference, i feel it has to store in  /nodes/{node_id}/LocalStorage/RawReference. if the node is virtual machine then raw_reference contains virtual disk detail, if node is physical device then raw_reference should have physical device details.

**Comment by GowthamShanmugam** [comment]
@brainfunked @shtripat @r0h4n

**Comment by shtripat** [comment]
Looks reasonable to me.

**Comment by r0h4n** [comment]
@GowthamShanmugam How are the current RawReference used by API and UI?

**Comment by brainfunked** [comment]
I agree with the change. I don't think the file is being used by either the API or the UI presently. I had asked for it to be synced for future use.

**Comment by GowthamShanmugam** [comment]
yes it is not used by anyone

**Comment by GowthamShanmugam** [comment]
@r0h4n We can close this issue
