### ISSUE TITLE
Errors when importing a Gluster Cluster 

### ISSUE THREAD

**Issue by mflannery** [Tendrl/node-agent#523]
After a successful tendrl-ansible install (or what looked successful, no errors at least) I get these errors when trying to import a gluster cluster into tendrl:

Events
info Processing Job 08dc1e3e-b15a-4e87-b10a-6978d0c01180 21 Jun 2017 04:42:16
info Running Flow tendrl.flows.ImportCluster 21 Jun 2017 04:42:16
info Acquired lock (08dc1e3e-b15a-4e87-b10a-6978d0c01180) for Node (b3df489e-4fcd-4cab-b6ae-32b02d0ec638) 21 Jun 2017 04:42:16
error Failed pre-run: tendrl.objects.Node.atoms.IsNodeTendrlManaged for flow: Import existing Gluster Cluster 21 Jun 2017 04:42:16
info Released lock (08dc1e3e-b15a-4e87-b10a-6978d0c01180) for Node (b3df489e-4fcd-4cab-b6ae-32b02d0ec638) 21 Jun 2017 04:42:16
error Job failed Traceback (most recent call last): File "/usr/lib/python2.7/site-packages/tendrl/commons/jobs/__init__.py", line 203, in _run the_flow.run() File "/usr/lib/python2.7/site-packages/tendrl/commons/flows/import_cluster/__init__.py", line 337, in run raise ex AtomExecutionFailedError: Atom Execution failed. Error: Error executing pre run function: tendrl.objects.Node.atoms.IsNodeTendrlManaged for flow: Import existing Gluster Cluster 21 Jun 2017 04:42:16

Mike

**Comment by nnDarshan** [comment]
@mflannery Before importing a gluster cluster we have pre checks to determine if all the nodes that are marked for import is managed by tendrl. By managed we mean if tandrl has all the required details(os, networks, memory, cpu etc) about the node. If these details are not available then we fail the import job. Which is the reason for failure in your case.

Note that, the above mentioned node details will be populated by tendrl-node-agent service that is started by the user. tendrl-node-agent will take some time to push all the node details to tendrl central store. If import is fired before this, it will fail saying "node is not managed".

Can you please try import after giving some time for tendrl-node-agent to sync the node details.

**Comment by r0h4n** [comment]
@mflannery Please respond to this issue, closing it till then
