### ISSUE TITLE
node-agent mesage handler not pushing message into etcd

### ISSUE THREAD

**Issue by GowthamShanmugam** [Tendrl/node-agent#530]
Node agent message handler is giving some error when message is received from socket.

result = self._run(*self.args, **self.kwargs)
TypeError: read_socket() takes exactly 2 arguments (3 given)
<Greenlet at 0x39e6410: <bound method MessageHandler.read_socket of <MessageHandler at 0x32eca50>>(<socket at 0x3a1eb50 fileno=13>, '')> failed with TypeError

**Comment by r0h4n** [comment]
What are the additional arguments mentioned in traceback `takes exactly 2 arguments (3 given)`
