### ISSUE TITLE
Collectd plugins dont load properly because it cant find utils

### ISSUE THREAD

**Issue by shtripat** [Tendrl/node-agent#568]
Collectd plugins dont load properly because it cant find utils, while starting the collectd service.

**Comment by r0h4n** [comment]
This is fixed temporarily, we need a stable fix @anmolbabu

**Comment by r0h4n** [comment]
@anmolbabu  please fix this

**Comment by anmolbabu** [comment]
Ack

**Comment by shtripat** [comment]
Is it still open?

**Comment by anmolbabu** [comment]
@shtripat This is open until we finalize between the current atomic plugin approach vs our custom approach as the fix to this then changes.

**Comment by anmolbabu** [comment]
This has been fixed permanently with https://github.com/Tendrl/node-agent/pull/599 and the same is merged.
@shtripat or @r0h4n Please close this issue as I am not allowed to do the same

**Comment by shtripat** [comment]
Closing as confirmed by @anmolbabu
