### ISSUE TITLE
Sync current CPU, memory and disk usage as part of the inventory sync

### ISSUE THREAD

**Issue by brainfunked** [Tendrl/node-agent#585]
Point in time usage data for every node's CPU, memory and disk usage [needs to be show in the UI](https://github.com/Tendrl/ui/issues/513). This information could to be synced as an attribute-value with the regular node sync.

In terms of the disk usage, the relevant information would be root partition usage, since this is just one data point to be displayed on the hosts list view, that is not related to any of the storage systems. Given the varied combination of mount points possible, it would be impossible to show just one single data point representing all the storage capacity utilisation on the host. Root partition utilisation may already be available as part of the disk inventory sync.

Memory and CPU utilisation attributes are almost certain to get updated at each sync. This poses a problem because two objects would get updated every sync (default 10 seconds) for every node managed by tendrl. Adding two attributes probably does not justify this increased load.

@r0h4n @nnDarshan @GowthamShanmugam what are your thoughts?

**Comment by brainfunked** [comment]
Discussion is ongoing on the storage utilisation at https://github.com/Tendrl/gluster-integration/issues/378. Storage utilisation should be added once we have a consensus.

**Comment by nnDarshan** [comment]
@brainfunked The patch for adding this is merged.
