### ISSUE TITLE
Import Cluster is failing

### ISSUE THREAD

**Issue by julienlim** [Tendrl/node-agent#597]
Scenario:
I tried to "Import" Cluster via Tendrl UI, but import task fails.

@Tendrl/qe @Tendrl/tendrl-core

=== Task Details (from UI) ===
Tasks  ImportCluster:  6c2bda13-b96e-4075-b7c9-f578d6a11025
Time Submitted:  30 Aug 2017 15:43:54
Status:  Failed

info Processing Job 6c2bda13-b96e-4075-b7c9-f578d6a11025 30 Aug 2017 03:43:55
info Running Flow tendrl.flows.ImportCluster 30 Aug 2017 03:43:55
info Acquired lock (6c2bda13-b96e-4075-b7c9-f578d6a11025) for Node (9a3129ef-4f9d-4e1c-b8fd-df00567a1056) 30 Aug 2017 03:43:55
info Importing (job: 7531581f-ebf2-4545-a1c7-c181d51fd322) Node 9a3129ef-4f9d-4e1c-b8fd-df00567a1056 to cluster 3dfe9397-d7cf-4af0-bcab-c912afadd3ef 30 Aug 2017 03:43:55
info Importing (job: ac6266e2-8863-4187-adbe-3ae0fca512b5) Node 9f16586c-31fc-44b4-a221-b38fa4044579 to cluster 3dfe9397-d7cf-4af0-bcab-c912afadd3ef 30 Aug 2017 03:43:56
info Check: Minimum required version (3.9.0) of Gluster Storage 30 Aug 2017 03:43:56
info Installing tendrl-gluster-integration on Node 0090df53-a65c-4eed-85e8-5eae05cf47bb 30 Aug 2017 03:43:56
info Generating configuration for tendrl-gluster-integration on Node 0090df53-a65c-4eed-85e8-5eae05cf47bb 30 Aug 2017 03:43:58
info Running tendrl-gluster-integration on Node 0090df53-a65c-4eed-85e8-5eae05cf47bb 30 Aug 2017 03:43:58
info Waiting for participant nodes [u'9a3129ef-4f9d-4e1c-b8fd-df00567a1056', u'0090df53-a65c-4eed-85e8-5eae05cf47bb', u'9f16586c-31fc-44b4-a221-b38fa4044579'] to be imported 3dfe9397-d7cf-4af0-bcab-c912afadd3ef 30 Aug 2017 03:43:58
info Released lock (6c2bda13-b96e-4075-b7c9-f578d6a11025) for Node (9a3129ef-4f9d-4e1c-b8fd-df00567a1056) 30 Aug 2017 03:43:58
info Processing Job ac6266e2-8863-4187-adbe-3ae0fca512b5 30 Aug 2017 03:43:58
info Running Flow tendrl.flows.ImportCluster 30 Aug 2017 03:43:58
info Acquired lock (ac6266e2-8863-4187-adbe-3ae0fca512b5) for Node (9f16586c-31fc-44b4-a221-b38fa4044579) 30 Aug 2017 03:43:58
info Check: Minimum required version (3.9.0) of Gluster Storage 30 Aug 2017 03:43:58
info Installing tendrl-gluster-integration on Node 9f16586c-31fc-44b4-a221-b38fa4044579 30 Aug 2017 03:43:58
info Processing Job 7531581f-ebf2-4545-a1c7-c181d51fd322 30 Aug 2017 03:43:59
info Running Flow tendrl.flows.ImportCluster 30 Aug 2017 03:43:59
info Acquired lock (7531581f-ebf2-4545-a1c7-c181d51fd322) for Node (9a3129ef-4f9d-4e1c-b8fd-df00567a1056) 30 Aug 2017 03:43:59
info Check: Minimum required version (3.9.0) of Gluster Storage 30 Aug 2017 03:43:59
info Installing tendrl-gluster-integration on Node 9a3129ef-4f9d-4e1c-b8fd-df00567a1056 30 Aug 2017 03:43:59
info Generating configuration for tendrl-gluster-integration on Node 9a3129ef-4f9d-4e1c-b8fd-df00567a1056 30 Aug 2017 03:44:00
info Running tendrl-gluster-integration on Node 9a3129ef-4f9d-4e1c-b8fd-df00567a1056 30 Aug 2017 03:44:00
info Waiting for participant nodes [u'9a3129ef-4f9d-4e1c-b8fd-df00567a1056'] to be imported 3dfe9397-d7cf-4af0-bcab-c912afadd3ef 30 Aug 2017 03:44:00
info Released lock (7531581f-ebf2-4545-a1c7-c181d51fd322) for Node (9a3129ef-4f9d-4e1c-b8fd-df00567a1056) 30 Aug 2017 03:44:00
info Generating configuration for tendrl-gluster-integration on Node 9f16586c-31fc-44b4-a221-b38fa4044579 30 Aug 2017 03:44:25
info Running tendrl-gluster-integration on Node 9f16586c-31fc-44b4-a221-b38fa4044579 30 Aug 2017 03:44:25
info Waiting for participant nodes [u'9f16586c-31fc-44b4-a221-b38fa4044579'] to be imported 3dfe9397-d7cf-4af0-bcab-c912afadd3ef 30 Aug 2017 03:44:25
info Released lock (ac6266e2-8863-4187-adbe-3ae0fca512b5) for Node (9f16586c-31fc-44b4-a221-b38fa4044579) 30 Aug 2017 03:44:25
error Cluster data sync still incomplete. Timing out 30 Aug 2017 03:55:22
error Failure in Job 6c2bda13-b96e-4075-b7c9-f578d6a11025 Flow tendrl.flows.ImportCluster with error: Traceback (most recent call last): File "/usr/lib/python2.7/site-packages/tendrl/commons/jobs/__init__.py", line 198, in process_job the_flow.run() File "/usr/lib/python2.7/site-packages/tendrl/commons/flows/import_cluster/__init__.py", line 44, in run super(ImportCluster, self).run() File "/usr/lib/python2.7/site-packages/tendrl/commons/flows/__init__.py", line 243, in run ret_val = self._execute_atom(atom_fqn) File "/usr/lib/python2.7/site-packages/tendrl/commons/flows/__init__.py", line 289, in _execute_atom raise ex AtomExecutionFailedError: Atom Execution failed. Error: Cluster data sync still incomplete. Timing out 30 Aug 2017 03:55:22
error Cluster data sync still incomplete. Timing out 30 Aug 2017 03:55:46
error Failure in Job 7531581f-ebf2-4545-a1c7-c181d51fd322 Flow tendrl.flows.ImportCluster with error: Traceback (most recent call last): File "/usr/lib/python2.7/site-packages/tendrl/commons/jobs/__init__.py", line 198, in process_job the_flow.run() File "/usr/lib/python2.7/site-packages/tendrl/commons/flows/import_cluster/__init__.py", line 44, in run super(ImportCluster, self).run() File "/usr/lib/python2.7/site-packages/tendrl/commons/flows/__init__.py", line 243, in run ret_val = self._execute_atom(atom_fqn) File "/usr/lib/python2.7/site-packages/tendrl/commons/flows/__init__.py", line 289, in _execute_atom raise ex AtomExecutionFailedError: Atom Execution failed. Error: Cluster data sync still incomplete. Timing out 30 Aug 2017 03:55:48
error Cluster data sync still incomplete. Timing out 30 Aug 2017 03:56:06
error Failure in Job ac6266e2-8863-4187-adbe-3ae0fca512b5 Flow tendrl.flows.ImportCluster with error: Traceback (most recent call last): File "/usr/lib/python2.7/site-packages/tendrl/commons/jobs/__init__.py", line 198, in process_job the_flow.run() File "/usr/lib/python2.7/site-packages/tendrl/commons/flows/import_cluster/__init__.py", line 44, in run super(ImportCluster, self).run() File "/usr/lib/python2.7/site-packages/tendrl/commons/flows/__init__.py", line 243, in run ret_val = self._execute_atom(atom_fqn) File "/usr/lib/python2.7/site-packages/tendrl/commons/flows/__init__.py", line 289, in _execute_atom raise ex AtomExecutionFailedError: Atom Execution failed. Error: Cluster data sync still incomplete. Timing out

=== Logs ===

There were no logs to be found in the following:
/var/log/tendrl/gluster-integration
/var/log/tendrl/monitoring-integration

This is the logs for /var/log/tendrl/node-agent/node-agent.log (excerpt):
see https://paste.fedoraproject.org/paste/sUvGNwoVKreVf4T1ZfrVcQ (EXPIRES SEPTEMBER 6, 2017 4:04 PM)

**Comment by r0h4n** [comment]
Fixed:
- https://github.com/Tendrl/gluster-integration/pull/384
- https://github.com/Tendrl/gluster-integration/pull/381
- https://github.com/Tendrl/node-agent/pull/596/files
