### ISSUE TITLE
Disable status related data pushes from collectd

### ISSUE THREAD

**Issue by anmolbabu** [Tendrl/node-agent#600]
Disable status related data pushes from collectd.
Monitoring-integration already pushes the cluster, volume, node and brick statuses to graphite increasing reliance on gluster-integration

**Comment by anmolbabu** [comment]
@rishubhjain Please let me know the list that is enabled from monitoring-integration and I can disable the corresponding from collectd plugins

**Comment by rishubhjain** [comment]
Cluster:
          status:
    Brick:
        status:
    Volume:
        subvol_count:
        status:
        state:
        pcnt_used:
        usable_capacity:
        used_capacity:
        rebal_status:
        geo_rep_session:
            count:
            total:
            up:
    Node:
        status:

Other than this, Brick count (total, up and down) -> cluster level, node_level, volume_level
Node_count (total, up and down) -> cluster level
Volume_Count (total, up and down) -> cluster level
@anmolbabu I guess Monitoring-integration will upload these counters,
@cloudbehl If possible please verify
@anmolbabu Can we progress once @cloudbehl verifies and acknowledge

**Comment by anmolbabu** [comment]
Closing this as PR to fix this is merged
