### ISSUE TITLE
tendrl services should run in selinux permissive domain

### ISSUE THREAD

**Issue by TimothyAsirJeyasing** [Tendrl/node-agent#604]
Currently tendrl packages needs the entire system to run without selinux security.
To avoid allowing the entire system in permissive, Tendrl requires a minimum selinux policy for its services.

**Comment by TimothyAsirJeyasing** [comment]
https://github.com/Tendrl/node-agent/pull/601

**Comment by mbukatov** [comment]
Could this issue be closed as WONTFIX? I see that related pull request was rejected and a different approach has been implemented in another repository.
