### ISSUE TITLE
Import of already imported cluster should fail

### ISSUE THREAD

**Issue by mkudlej** [Tendrl/node-agent#605]
Reproducer:
1. Two users open Tendrl web page for importing cluster. There is one cluster **X** ready for import.
2. First user imports cluster **X**.
3. If cluster **X** is imported, second user tries to import cluster **X**.
First import job should pass and second one should fail. In other words there should be check if cluster is already imported in *import flow*.

etcd-3.1.9-1.el7.x86_64
glusterfs-4.0dev-0.108.gitb1352d0.el7.centos.x86_64
glusterfs-api-4.0dev-0.108.gitb1352d0.el7.centos.x86_64
glusterfs-cli-4.0dev-0.108.gitb1352d0.el7.centos.x86_64
glusterfs-client-xlators-4.0dev-0.108.gitb1352d0.el7.centos.x86_64
glusterfs-fuse-4.0dev-0.108.gitb1352d0.el7.centos.x86_64
glusterfs-geo-replication-4.0dev-0.108.gitb1352d0.el7.centos.x86_64
glusterfs-libs-4.0dev-0.108.gitb1352d0.el7.centos.x86_64
glusterfs-server-4.0dev-0.108.gitb1352d0.el7.centos.x86_64
python2-gluster-4.0dev-0.108.gitb1352d0.el7.centos.x86_64
python-etcd-0.4.5-1.noarch
rubygem-etcd-0.3.0-1.el7.centos.noarch
tendrl-api-1.5.1-1.el7.centos.noarch
tendrl-api-httpd-1.5.1-1.el7.centos.noarch
tendrl-commons-1.5.1-1.el7.centos.noarch
tendrl-gluster-integration-1.5.1-1.el7.centos.noarch
tendrl-monitoring-integration-1.5.1-1.el7.centos.noarch
tendrl-node-agent-1.5.1-1.el7.centos.noarch
tendrl-ui-1.5.1-1.el7.centos.noarch

**Comment by r0h4n** [comment]
Fixed
