### ISSUE TITLE
Introducing a new flag in message payload to separate alert from notification

### ISSUE THREAD

**Issue by GowthamShanmugam** [Tendrl/node-agent#609]
Currently, node-agent considering if alert came with notice priority then it is alert, and sending email notification also. Problem is notification messages no need to notify via email. It has to go to /messages/events only.
To separate notification message from the alert message, we need some flag.

In message payload, we are going to give field called "notify_only = True" for confirming the message is notification message, ie (priority: Notice, and payload has notify_only = True). If this field not present in message payload then we consider this is an alert,  ie (it only have priority: Notice).

* priority: Notice + payload has notify_only = True  is notification
*  priority: Notice is alert

**Comment by GowthamShanmugam** [comment]
@shtripat @nthomas-redhat @r0h4n @anmolbabu

**Comment by r0h4n** [comment]
@brainfunked Please comment on this. 

@GowthamShanmugam this is very confusing, Probably mention that by "Notification" you mean the messages that show up in Notification UI drop down.

**Comment by shtripat** [comment]
@GowthamShanmugam this could be closed I feel as the changes are merged.

**Comment by GowthamShanmugam** [comment]
@r0h4n this is merged am i close this?
