### ISSUE TITLE
Rebalance counters from get-state apply to node-level under volume and not to volume itself

### ISSUE THREAD

**Issue by anmolbabu** [Tendrl/node-agent#638]
Rebalance counters from get-state apply to node-level(node on which get-state is run) under volume and not to volume itself although, the key(for ex: volume1.rebalance.failures) for the same in get-state o/p seems to suggest that it applies to volume itself.

**Comment by r0h4n** [comment]
Is this resolved @anmolbabu

**Comment by anmolbabu** [comment]
Yes the PR to fix this on collectd side for which this issue was raised is merged. Closing this now.
