### ISSUE TITLE
Etcd operation not working when we use HTTPS client certificates

### ISSUE THREAD

**Issue by GowthamShanmugam** [Tendrl/node-agent#640]
I have uncommented etcd_ca_cert_file, etcd_cert_file, etcd_key_file and added proper key paths in node-agent agent conf file. After that i have started node-agent. Node-agent is failed with exception:
   TypeError: __init__() got an unexpected keyword argument 'server_hostname'

Traceback (most recent call last):
  File "/usr/bin/tendrl-node-agent", line 9, in <module>
    load_entry_point('tendrl-node-agent==1.5.2', 'console_scripts', 'tendrl-node-agent')()
  File "/usr/lib/python2.7/site-packages/tendrl/node_agent/manager/__init__.py", line 40, in main
    node_agent.NodeAgentNS()
  File "/usr/lib/python2.7/site-packages/tendrl/node_agent/__init__.py", line 16, in __init__
    super(NodeAgentNS, self).__init__(ns_name, ns_src)
  File "/usr/lib/python2.7/site-packages/tendrl/commons/__init__.py", line 44, in __init__
    self.setup_common_objects()
  File "/usr/lib/python2.7/site-packages/tendrl/commons/__init__.py", line 274, in setup_common_objects
    print NS._int.wclient.read("/foo") 
  File "/usr/lib/python2.7/site-packages/etcd/client.py", line 597, in read
    timeout=timeout)
  File "/usr/lib/python2.7/site-packages/etcd/client.py", line 855, in wrapper
    params=params, timeout=timeout)
  File "/usr/lib/python2.7/site-packages/etcd/client.py", line 923, in api_execute
    preload_content=False)
  File "/usr/lib/python2.7/site-packages/urllib3/request.py", line 68, in request
    **urlopen_kw)
  File "/usr/lib/python2.7/site-packages/urllib3/request.py", line 81, in request_encode_url
    return self.urlopen(method, url, **urlopen_kw)
  File "/usr/lib/python2.7/site-packages/urllib3/poolmanager.py", line 247, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 341, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 762, in _validate_conn
    conn.connect()
  File "/usr/lib/python2.7/site-packages/urllib3/connection.py", line 238, in connect
    ssl_version=resolved_ssl_version)
  File "/usr/lib/python2.7/site-packages/urllib3/util/ssl_.py", line 258, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib64/python2.7/ssl.py", line 350, in wrap_socket
    _context=self)
TypeError: __init__() got an unexpected keyword argument 'server_hostname'

 
Using pdb what i found is, in ssl.py there is a class called SSLSocket when a flow try to call SSLSocket class the control goes into gevent.ssl.SSLSocket class. ssl.SSLSocket class is over written by gevent.ssl.SSLSocket class. When it is over written means in /usr/lib/python2.7/site-packages/tendrl/node_agent/__init__.py file monkey.patch_all() is actaully doing this overwittren.

I have created python file and i tried to read and write etcd using key files, it works fine.

**Comment by GowthamShanmugam** [comment]
@r0h4n @shtripat @nthomas-redhat

**Comment by r0h4n** [comment]
Please provide version numbers for rpms "python", "gevent"

**Comment by GowthamShanmugam** [comment]
Python 2.7.5,  python-gevent-1.0-3

**Comment by mbukatov** [comment]
I see the same issue in my setup, see: https://gist.github.com/mbukatov/a861ab9a3aa9b1db539441b44483ffbb

Versions I use:

```
# rpm -qa | grep tendrl
tendrl-monitoring-integration-1.5.2-20171005T174313.ed38272.noarch
tendrl-commons-1.5.2-20171004T104238.6d5ffef.noarch
tendrl-api-1.5.2-20170927T205654.a9e16c0.noarch
tendrl-ui-1.5.2-20170928T151925.1cdc907.noarch
tendrl-grafana-plugins-1.5.2-20171005T174313.ed38272.noarch
tendrl-node-agent-1.5.2-20171004T105957.709badc.noarch
tendrl-notifier-1.5.2-20170927T205657.566bfa0.noarch
tendrl-api-httpd-1.5.2-20170927T205654.a9e16c0.noarch
# rpm -qa | grep etcd
etcd-3.2.5-1.el7.x86_64
rubygem-etcd-0.3.0-1.el7.centos.noarch
python-etcd-0.4.5-1.noarch
# rpm -qa | grep gevent
python-gevent-1.0-3.el7.x86_64
```

**Comment by r0h4n** [comment]
Related: https://github.com/gevent/gevent/issues/702

**Comment by r0h4n** [comment]
I could get this thing working by updating the "python-gevent" rpm to >1.0.2 

I got success using gevent==1.1.0

**Comment by r0h4n** [comment]
I tested this today again, seems to work fine, please check below env details

```
[root@k4n0 ~]# python --version
Python 2.7.5

[root@k4n0 ~]# lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.4.1708 (Core) 
Release:        7.4.1708
Codename:       Core

[root@k4n0 ~]# rpm -qa | grep gevent
python-gevent-1.0-3.el7.x86_64

[root@k4n0 ~]# rpm -qa | grep requests
python-requests-2.6.0-1.el7_1.noarch

[root@k4n0 ~]# rpm -qa | grep urllib3
python-urllib3-1.10.2-3.el7.noarch

```

**Comment by GowthamShanmugam** [comment]
@r0h4n i have tested this als,  it works fine

**Comment by r0h4n** [comment]
@GowthamShanmugam You mean to say you have tested using env mentioned at https://github.com/Tendrl/node-agent/issues/640#issuecomment-334666967  and it works alright?

@mbukatov please try this out

**Comment by r0h4n** [comment]
Opening this again, 

@TimothyAsir @mbukatov seems like we have a hard dependency on python-gevent>=1.0.3,  could you guys please test this and confirm before we update Tendrl commons spec file for adding the requirement

**Comment by mbukatov** [comment]
@r0h4n I tested what would happen when I replace python-gevent 1.0 from rpm package with python gevent 1.2.2 from pip (which is testing only hack) and noticed a different error which prevents node agent to work: https://gist.github.com/mbukatov/c6394a60709d94631c9cd73219dd8d1c

The connection is rejected, but when I try this on the same machine to check if tls is configured right, I see that it works:

```
# curl --cacert /etc/pki/tls/certs/ca-usmqe.crt --cert /etc/pki/tls/certs/etcd.crt --key /etc/pki/tls/private/etcd.key https://mbukatov-usm1-server.example.com:2379/v2/keys/
{"action":"get","node":{"dir":true,"nodes":[{"key":"/nodes","dir":true,"modifiedIndex":8,"createdIndex":8},{"key":"/indexes","dir":true,"modifiedIndex":127,"createdIndex":127},{"key":"/clusters","dir":true,"modifiedIndex":669,"createdIndex":669},{"key":"/networks","dir":true,"modifiedIndex":382,"createdIndex":382},{"key":"/alerting","dir":true,"modifiedIndex":430,"createdIndex":430},{"key":"/messages","dir":true,"modifiedIndex":463,"createdIndex":463},{"key":"/queue","dir":true,"modifiedIndex":4633,"createdIndex":4633},{"key":"/notifications","dir":true,"modifiedIndex":7139,"createdIndex":7139}]}}
```

**Comment by r0h4n** [comment]
Please try with specific rpms and Centos version as mentioned in comment https://github.com/Tendrl/node-agent/issues/640#issuecomment-334666967

Also ensure `python-gevent-1.0-3.el7.x86_64` is installed

It works for me using above combination of Centos and rpms

**Comment by GowthamShanmugam** [comment]
in that code past i am seeing etcd ip like http://0.0.0.0:2379?

**Comment by mbukatov** [comment]
See the updated gist here: https://gist.github.com/mbukatov/8e0b65dcd1e30bf0c5fcbe9092fc5d7f

@r0h4n I redeployed and retried on a clean machine, using snapshot builds from master branch, installed via tendrl-ansible work in progress branch (commit https://github.com/mbukatov/tendrl-ansible/commit/900280319b45fc69c42d6129496355ab3cdb94b9), and I can reproduce the issue consistently. The package versions you mention matches versions I use there.

@GowthamShanmugam I have added the conf file into the gist.

**Comment by r0h4n** [comment]
@mbukatov Please try making changes from this PR on your env https://github.com/Tendrl/node-agent/pull/642

Let me know if it works, I have pulled this patch from this issue https://github.com/gevent/gevent/issues/702

**Comment by mbukatov** [comment]
@r0h4n I did a hack to path the file you updated:

```
# curl https://raw.githubusercontent.com/Tendrl/node-agent/1ccc26c96b3ce79847811f7648bb927e7c7227ea/tendrl/node_agent/__init__.py > /usr/lib/python2.7/site-packages/tendrl/node_agent/__init__.py
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current 
                                 Dload  Upload   Total   Spent    Left  Speed   
100  2116  100  2116    0     0   1677      0  0:00:01  0:00:01 --:--:--  1679 
```

Retried and it failed with:

```
Oct 06 12:51:04 mbukatov-usm1-server.example.com systemd[1]: Started A python agent local to every managed storage node in the sds cluster.
Oct 06 12:51:04 mbukatov-usm1-server.example.com systemd[1]: Starting A python agent local to every managed storage node in the sds cluster...
Oct 06 12:51:05 mbukatov-usm1-server.example.com tendrl-node-agent[16809]: Creating namespace.node_agent from source tendrl.node_agentnamespace.node_agent created!Finding objects in namespace.node_agent.objectsRegistering object namespace.node_agent.objects.ClusterAlertCountersFinding atoms in namesp
Oct 06 12:51:05 mbukatov-usm1-server.example.com tendrl-node-agent[16809]: onMessage.flowsFinding flows in namespace.node_agent.flowsRegistering flow namespace.node_agent.flows.GenerateJournalMappingSetup Tendrl definitions (.yml)for namespace.node_agentValidating registered (.py) flows in namespace.
Oct 06 12:51:05 mbukatov-usm1-server.example.com tendrl-node-agent[16809]: tendrl.objects.ClusterAlert.atomsFinding flows in namespace.tendrl.objects.ClusterAlert.flowsRegistering object namespace.tendrl.objects.ClusterNodeContextFinding atoms in namespace.tendrl.objects.ClusterNodeContext.atomsFindi
Oct 06 12:51:05 mbukatov-usm1-server.example.com tendrl-node-agent[16809]: drl.objects.Alert.flowsRegistering object namespace.tendrl.objects.NodeAlertFinding atoms in namespace.tendrl.objects.NodeAlert.atomsFinding flows in namespace.tendrl.objects.NodeAlert.flowsRegistering object namespace.tendrl.
Oct 06 12:51:05 mbukatov-usm1-server.example.com tendrl-node-agent[16809]: gistering flow namespace.tendrl.flows.AuthorizeSshKeyRegistering flow namespace.tendrl.flows.CreateClusterRegistering flow namespace.tendrl.flows.ExpandClusterRegistering flow namespace.tendrl.flows.ImportClusterRegistering fl
Oct 06 12:51:05 mbukatov-usm1-server.example.com tendrl-node-age[16809]: Starting new HTTPS connection (1): 10.34.108.90
Oct 06 12:51:05 mbukatov-usm1-server.example.com tendrl-node-agent[16809]: Request to server https://10.34.108.90:2379 failed: SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:579)'),)
Oct 06 12:51:05 mbukatov-usm1-server.example.com tendrl-node-age[16809]: Request to server https://10.34.108.90:2379 failed: SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:579)'),)
Oct 06 12:51:05 mbukatov-usm1-server.example.com tendrl-node-agent[16809]: Traceback (most recent call last):
Oct 06 12:51:05 mbukatov-usm1-server.example.com tendrl-node-agent[16809]: File "/usr/bin/tendrl-node-agent", line 9, in <module>
Oct 06 12:51:05 mbukatov-usm1-server.example.com tendrl-node-agent[16809]: load_entry_point('tendrl-node-agent==1.5.2', 'console_scripts', 'tendrl-node-agent')()
Oct 06 12:51:05 mbukatov-usm1-server.example.com tendrl-node-agent[16809]: File "/usr/lib/python2.7/site-packages/tendrl/node_agent/manager/__init__.py", line 42, in main
Oct 06 12:51:05 mbukatov-usm1-server.example.com tendrl-node-agent[16809]: TendrlNS()
Oct 06 12:51:05 mbukatov-usm1-server.example.com tendrl-node-agent[16809]: File "/usr/lib/python2.7/site-packages/tendrl/commons/__init__.py", line 45, in __init__
Oct 06 12:51:05 mbukatov-usm1-server.example.com tendrl-node-agent[16809]: self.setup_common_objects()
Oct 06 12:51:05 mbukatov-usm1-server.example.com tendrl-node-agent[16809]: File "/usr/lib/python2.7/site-packages/tendrl/commons/__init__.py", line 297, in setup_common_objects
Oct 06 12:51:05 mbukatov-usm1-server.example.com tendrl-node-agent[16809]: self.current_ns.objects.NodeContext()
Oct 06 12:51:05 mbukatov-usm1-server.example.com tendrl-node-agent[16809]: File "/usr/lib/python2.7/site-packages/tendrl/commons/objects/node_context/__init__.py", line 34, in __init__
Oct 06 12:51:05 mbukatov-usm1-server.example.com tendrl-node-agent[16809]: self.node_id).value
Oct 06 12:51:05 mbukatov-usm1-server.example.com tendrl-node-agent[16809]: File "/usr/lib/python2.7/site-packages/etcd/client.py", line 597, in read
Oct 06 12:51:05 mbukatov-usm1-server.example.com tendrl-node-agent[16809]: timeout=timeout)
Oct 06 12:51:05 mbukatov-usm1-server.example.com tendrl-node-agent[16809]: File "/usr/lib/python2.7/site-packages/etcd/client.py", line 893, in wrapper
Oct 06 12:51:05 mbukatov-usm1-server.example.com tendrl-node-agent[16809]: cause=e
Oct 06 12:51:05 mbukatov-usm1-server.example.com tendrl-node-agent[16809]: etcd.EtcdConnectionFailed: Connection to etcd failed due to SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:579)'),)
Oct 06 12:51:05 mbukatov-usm1-server.example.com systemd[1]: tendrl-node-agent.service: main process exited, code=exited, status=1/FAILURE
Oct 06 12:51:05 mbukatov-usm1-server.example.com systemd[1]: Unit tendrl-node-agent.service entered failed state.
Oct 06 12:51:05 mbukatov-usm1-server.example.com systemd[1]: tendrl-node-agent.service failed.
```

But as I said before, I'm able to do the following, so the tls auth seems to be configured right:


```
# curl --cacert /etc/pki/tls/certs/ca-usmqe.crt --cert /etc/pki/tls/certs/etcd.crt --key /etc/pki/tls/private/etcd.key https://mbukatov-usm1-server.example.com:2379/v2/keys/
{"action":"get","node":{"dir":true}}
```
