### ISSUE TITLE
alert counter to be initialized even the alert count is zero.

### ISSUE THREAD

**Issue by cloudbehl** [Tendrl/node-agent#643]
so the problem is if there are no alerts for the host or volume the alert_counters object is not getting initialized and UI is showing Is showing"NA". This should not be the case the alert_count should be initialized with 0 value if there are no alerts.

**Comment by cloudbehl** [comment]
@GowthamShanmugam @r0h4n @shtripat @anivargi

**Comment by GowthamShanmugam** [comment]
This issue is fixed, @cloudbehl please verify and close this

**Comment by r0h4n** [comment]
@cloudbehl Is this verified?

**Comment by cloudbehl** [comment]
@r0h4n @anivargi is adding alert count to the API and once it's available in API I can verify it UI and then I will close it.

**Comment by r0h4n** [comment]
@cloudbehl  @anivargi  let me know if this is not done yet. Closing
