### ISSUE TITLE
Node-agent is failing with package dependency issue 

### ISSUE THREAD

**Issue by GowthamShanmugam** [Tendrl/node-agent#646]
Unable to start node-agent, it fails with some package dependency issue 

Traceback (most recent call last):
  File "/usr/bin/tendrl-node-agent", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 3007, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 728, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 626, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: pyasn1>=0.1.7

**Comment by GowthamShanmugam** [comment]
@TimothyAsir @r0h4n

**Comment by r0h4n** [comment]
The traceback clearly says package `pyasn1>=0.1.7` not found. Is this related to pysnmp usage in Tendrl/notifier?

**Comment by GowthamShanmugam** [comment]
pysnmp requires pyasn1 as dependency so @TimothyAsir is added pyasn1 in pysnmp build, so it causing this issue

**Comment by r0h4n** [comment]
There seems to be a conflict with python2-pyasn1 (repo: Tendrl/dependencies) vs python2-pyasn1 (repo: Centos)

I have removed python2-pyasn1 from repo: Tendrl/dependencies , please dont add it until we have a final word on the conflict @TimothyAsir
