### ISSUE TITLE
Issue in provisioner tag re assignment on provisioner node down senario.

### ISSUE THREAD

**Issue by nnDarshan** [Tendrl/node-agent#655]
When a provisioner node goes down, a new node should claim this tag. But this does not seem to be working.
From, basic analysis. It looks like the key `indexes/tags/provisioner` does not have a ttl set. Because of which. Even if provisioner node goes down the value at the above location remains intact. Because of which, A new node cannot mark itself as provisioner (basically https://github.com/Tendrl/node-agent/blob/master/tendrl/node_agent/node_sync/services_and_index_sync.py#L73 fails as prevExists=True)

**Comment by nnDarshan** [comment]
@r0h4n @nthomas-redhat Please have a look

**Comment by nthomas-redhat** [comment]
@nnDarshan , could you please verify this ?

**Comment by nnDarshan** [comment]
works as expected in latest master
