### ISSUE TITLE
Config files are not removed after rpm un-installation

### ISSUE THREAD

**Issue by nthomas-redhat** [Tendrl/node-agent#659]
/etc/tendrl/node-agent directory needs to be removed on un-install

**Comment by r0h4n** [comment]
@TimothyAsir  any updates on this?

**Comment by r0h4n** [comment]
@TimothyAsir  @nthomas-redhat  Is this fixed?

**Comment by TimothyAsirJeyasing** [comment]
Yes its fixed already, we can close this issue
