### ISSUE TITLE
When cluster import task fails and the cluster is shown as ok in Tendrl UI, the problem is not reported anywhere else or it's not possible to recover directly

### ISSUE THREAD

**Issue by mbukatov** [Tendrl/node-agent#662]
## Description

When one reproduces use case as described in https://github.com/Tendrl/node-agent/issues/627, the Import Cluster task will fail, but otherwise the cluster is shown on Clusters page as ok, without any error reported.

## Screenshots for quick understanding of the situation

Import Cluster task failed (during installation of gluster integration component on one machine):

![screenshot_20171102_163353](https://user-images.githubusercontent.com/4759819/32334869-dd5eaf8e-bfeb-11e7-947b-30f0a6897fce.png)

But the cluster looks fine in Clusters page:

![screenshot_20171102_163526](https://user-images.githubusercontent.com/4759819/32334884-e5f249b2-bfeb-11e7-8c14-f363d3b910bb.png)

For full context, see the issue linked above.

## Version

Latest snapshot build from master branch (it's going to be part of upcoming 1.5.4 version):

```
[root@mbukatov-usm1-server ~]# rpm -qa | grep tendrl | sort
tendrl-api-1.5.3-20171102T102141.e899dff.noarch
tendrl-api-httpd-1.5.3-20171102T102141.e899dff.noarch
tendrl-commons-1.5.3-20171101T103313.c987736.noarch
tendrl-grafana-plugins-1.5.3-20171101T130858.f752f23.noarch
tendrl-grafana-selinux-1.5.3-20171013T090621.ffb1b7f.noarch
tendrl-monitoring-integration-1.5.3-20171101T130858.f752f23.noarch
tendrl-node-agent-1.5.3-20171101T112542.0d676e6.noarch
tendrl-notifier-1.5.3-20171030T164233.702f1a5.noarch
tendrl-selinux-1.5.3-20171013T090621.ffb1b7f.noarch
tendrl-ui-1.5.3-20171102T121438.a0b889b.noarch
```

## Further Discussion Needed

There are multiple questions:

* Is it expected behavior for this particular use case, to show cluster as ok when gluster integration not installed on one machine of the cluster? Note that from GlusterFS point of view, the cluster is really healthy, because gluster doesn't care about missing gluster-ingegration component, but from Tendrl's point of view, this is a problem.
* When admin figures out what's wrong (reading the error as reported by Tendrl), what options does Tendrl provide to fix this issue? Eg. admin fixes temporary problem with availability of tendrl repo and now what?
* When logs for failed Cluster Import tasks are dropped after few days, there will be no clear indication what's wrong anywhere in the Tendrl UI. Is this ok? And if not, how could we address it?
* How could be admin sure that nothing else is missing wrong with the setup tendrl needs to do on storage machines?
* Looking at design document https://redhat.invisionapp.com/share/8QCOEVEY9#/screens/244738628, it looks like we should mark the cluster so that it's clear that import failed. Would that apply in this particular case?

@Tendrl/tendrl-core @Tendrl/tendrl-qe @julienlim

**Comment by julienlim** [comment]
@Tendrl/tendrl-core @Tendrl/tendrl-qe 

Failures do need to be bubbled up back on the cluster list page where Import cluster was triggered, and buttons should not be enabled (to see Details, Dashboard, etc.) if import cluster failed.  Looks like a bug that needs to be addressed.

**Comment by r0h4n** [comment]
@gnehapk Are you checking if `cluster.import_status != "failed"`  while deciding whether a cluster is importable or not?

cc @anivargi

**Comment by gnehapk** [comment]
@r0h4n UI is displaying "Managed" field "Yes" only if the cluster's `is_managed` property is set to "yes".

@mbukatov Can you please share the API response of  `/clusters`  you received on cluster list page.

**Comment by r0h4n** [comment]
@gnehapk Use the `cluster.import_status != "failed"` condition along with `cluster.is_managed == "Yes"`

**Comment by cloudbehl** [comment]
@julienlim If the import cluster is failed are we going to enable the import button for a cluster or the Import button will remain disabled?

**Comment by julienlim** [comment]
@cloudbehl If Import cluster failed, ideally we should provide feedback to user how to resolve/troubleshoot and remediate the issue(s), and yes enable the Import button so they can get re-attempt an Import after they've resolved the issue(s).

It's not clear me if the resolution is something handled in the UI currently or outside the UI as ideally we would identify all the failure modes and provide proper guidance on how to resolve each of those failure modes from the UI.

**Comment by r0h4n** [comment]
`resolve/troubleshoot` import cluster failures requires very accurate analysis of the error logs or error conditions and availability of solutions for such logs. It also requires Tendrl to know all failure modes. How is such sort of data to be gathered?

**Comment by julienlim** [comment]
@r0h4n @brainfunked 

At the very least, we should make it easy for users to know which logs to look at (even if they are not centralized initially) and what to check for and guide them through troubleshooting steps of what one should check for when import cluster fails.

**Comment by r0h4n** [comment]
I would say we approach this issue via code and more meaningful logs.

Code: We should discuss in detail the current import flow, and add more pre-flight checks before the tendrl-gluster-integration is configured and before the monitoring things are setup. Pre-flight checks can include repo verification, addition of missing repos etc.

Additional to above, we should add meaningful error logs on failure of any pre-flight/import step.

**Comment by r0h4n** [comment]
To avoid confusion,  Tendrl does not provide a retry on a failed import, mainly because Tendrl Import Flow and the atoms inside the flow do not have any revert functionality as of now. We will support retries for failed import (without requiring etcd cleanup) in future.

In case of failed imports as of today, users should refer Tendrl documentation (TODO) for cleaning up Tendrl central store and re-trying the Import after that.

**Comment by r0h4n** [comment]
Tendrl will provide  flows called "unmanage cluster" and "delete cluster", in case of a failed import, user must "delete cluster" and try to import cluster again.

**Comment by r0h4n** [comment]
Closing this one since we now provide unmanage cluster API and also provide cluster.errors in case there are problems with the cluster
