### ISSUE TITLE
Collectd pushes volume heal info to wrong brick

### ISSUE THREAD

**Issue by GowthamShanmugam** [Tendrl/node-agent#685]
Collectd pushes heal info under brick using subvolume index and brick index, Here the problem is when the particular brick is deleted Cluster Topology have old volume and brick info so when healing info plugin try to push heal info it actually pushing under a wrong brick. 
So after deleted brick info again collected created brick entry in graphite.

Need to check node id while pushing heal info under brick.

**Comment by nthomas-redhat** [comment]
Closing the issue as it is already fixed
