### ISSUE TITLE
Modify collectd plugin for volume heal info to use `heal info` and `heal info split-brain` options

### ISSUE THREAD

**Issue by shtripat** [Tendrl/node-agent#688]
The currently used command `gluster v heal <volname> statistics` is not supported. We rather should use the below commands

- gluster v heal <volname> info
- gluster v heal <volname> info split-brain

and accordingly show these values in grafana dashboard

**Comment by shtripat** [comment]
@cloudbehl ^^^

**Comment by nthomas-redhat** [comment]
Closing the issue as the fix is already in
