### ISSUE TITLE
Correct rebalance data calculation logic

### ISSUE THREAD

**Issue by shtripat** [Tendrl/node-agent#690]
Currently the logic doesnt consider if the get-state output for rebalance data reports Bytes/KB/MB/GB/TB/PB. It just removed the numeric part and populates to graphite. We should change the logic to calculate the correct value in say MB always and report to graphite so that grafana dashboard can show the same as MBs

**Comment by nthomas-redhat** [comment]
Closing the issue as the fix is already in
