### ISSUE TITLE
Expose a way for node_agent to receive events and push the same to etcd and add generic atom to check service status

### ISSUE THREAD

**Issue by anmolbabu** [Tendrl/node-agent#70]
The node-agent needs to expose a socket to which the collectd(performance monitoring threshold breaches) or the bridges(sds entity state changes) can communicate the events to etcd.The node-agent needs to be single channel of updates to alerts/events in etcd.

There needs to be an atom to check the status of a service that can be used to check if the service was started properly after its configuration. This in particular is currently required to facilitate checking of collectd service post its configuration but it can be built in a generic way so that any service status can be checked as part of configuring any service.

tendrl-spec: Tendrl/specifications#18

**Comment by r0h4n** [comment]
This needs to be linked to a spec
