### ISSUE TITLE
ERROR - node_sync disks sync failed:  - KeyError in /var/log/messages

### ISSUE THREAD

**Issue by dahorak** [Tendrl/node-agent#719]
I've spotted following error repeated every minute in `/var/log/messages` on all servers (Tendrl server, Gluster servers) on testing cluster in CentOS CI:

```
Feb 12 13:51:34 n5 tendrl-node-agent: 2018-02-12 13:51:34.282763+00:00 - node_agent - /usr/lib/python2.7/site-packages/tendrl/node_agent/node_sync/disk_sync.py:65 - sync - ERROR - node_sync disks sync failed:  - KeyError: [{u'function': u'__bootstrap', u'line': 785, u'file': u'/usr/lib64/python2.7/threading.py', u'statement': u'self.__bootstrap_inner()'}, {u'function': u'__bootstrap_inner', u'line': 812, u'file': u'/usr/lib64/python2.7/threading.py', u'statement': u'self.run()'}, {u'function': u'run', u'line': 765, u'file': u'/usr/lib64/python2.7/threading.py', u'statement': u'self.__target(*self.__args, **self.__kwargs)'}, {u'function': u'sync', u'line': 12, u'file': u'/usr/lib/python2.7/site-packages/tendrl/node_agent/node_sync/disk_sync.py', u'statement': u'disks = get_node_disks()'}, {u'function': u'get_node_disks', u'line': 118, u'file': u'/usr/lib/python2.7/site-packages/tendrl/node_agent/node_sync/disk_sync.py', u'statement': u'parent = disks_map[devlist["parent_hardware_id"]]'}]
```
Formatted for better readability:
```
Feb 12 13:51:34 n5 tendrl-node-agent: 2018-02-12 13:51:34.282763+00:00 
  - node_agent 
  - /usr/lib/python2.7/site-packages/tendrl/node_agent/node_sync/disk_sync.py:65 
  - sync - ERROR - node_sync disks sync failed:  - KeyError:
[
  {u'function': u'__bootstrap', u'line': 785, u'file': u'/usr/lib64/python2.7/threading.py', u'statement': u'self.__bootstrap_inner()'},
  {u'function': u'__bootstrap_inner', u'line': 812, u'file': u'/usr/lib64/python2.7/threading.py', u'statement': u'self.run()'},
  {u'function': u'run', u'line': 765, u'file': u'/usr/lib64/python2.7/threading.py', u'statement': u'self.__target(*self.__args, **self.__kwargs)'},
  {u'function': u'sync', u'line': 12, u'file': u'/usr/lib/python2.7/site-packages/tendrl/node_agent/node_sync/disk_sync.py', u'statement': u'disks = get_node_disks()'},
  {
    u'function': u'get_node_disks',
    u'line': 118,
    u'file': u'/usr/lib/python2.7/site-packages/tendrl/node_agent/node_sync/disk_sync.py',
    u'statement': u'parent = disks_map[devlist["parent_hardware_id"]]'
  }
]
```
I was able to debug it via following steps. Variable `devlist` have following content:
```
{
'device_files': '',
'hardware_class': '',
'partition_name': '',
'model': '',
'hardware_id': '',
'config_status': '',
'sysfs_id': '',
'parent_hardware_id': ''
}
```
Which means, that it is properly initialized [in disk_sync.py on line 77](https://github.com/Tendrl/node-agent/blob/master/tendrl/node_agent/node_sync/disk_sync.py#L77), but not filled up in the next loop (bellow line 86).

The reason is empty output from `hwinfo --partition` command:
```
# hwinfo --partition
#  echo $?                                            
0
```
While output from `lsblk` command looks like this:
```
# lsblk 
NAME             MAJ:MIN RM   SIZE RO TYPE  MOUNTPOINT
sda                8:0    0   447G  0 disk  
└─mpatha         253:0    0   447G  0 mpath 
  ├─mpatha1      253:1    0   500M  0 part  /boot
  └─mpatha2      253:2    0 446.5G  0 part  
    ├─vg_n5-root 253:3    0 444.4G  0 lvm   /
    └─vg_n5-swap 253:4    0   2.1G  0 lvm   [SWAP]
sdb                8:16   0   447G  0 disk  
└─mpatha         253:0    0   447G  0 mpath 
  ├─mpatha1      253:1    0   500M  0 part  /boot
  └─mpatha2      253:2    0 446.5G  0 part  
    ├─vg_n5-root 253:3    0 444.4G  0 lvm   /
    └─vg_n5-swap 253:4    0   2.1G  0 lvm   [SWAP]
```

**So the root cause of the issue seems to be the fact, that there are no partitions on any of the disk on the machine.**
PV/VG/LV is created on DM Multipath device which is using directly whole disk.

**Comment by dahorak** [comment]
Additional info - output from `hwinfo --disk` command:
```
# hwinfo --disk
30: IDE 00.0: 10600 Disk                                        
  [Created at block.245]
  Unique ID: 3OOL.nkkuEMg7MeD
  Parent ID: VCu0.FcOdDptW9P4
  SysFS ID: /class/block/sda
  SysFS BusID: 0:0:0:0
  SysFS Device Link: /devices/pci0000:00/0000:00:01.0/0000:01:00.0/ata1/host0/target0:0:0/0:0:0:0
  Hardware Class: disk
  Model: "SMvD133509528D80"
  Device: "SMvD133509528D80"
  Revision: "n/a"
  Serial ID: "133509528D80"
  Driver: "ahci", "sd"
  Driver Modules: "ahci"
  Device File: /dev/sda
  Device Files: /dev/sda, /dev/disk/by-id/ata-SMvD133509528D80_133509528D80, /dev/disk/by-id/wwn-0x5000c5001feb99f0, /dev/disk/by-path/pci-0000:01:00.0-ata-1.0
  Device Number: block 8:0-8:15
  BIOS id: 0x80
  Geometry (Logical): CHS 58352/255/63
  Size: 937426944 sectors a 512 bytes
  Capacity: 447 GB (479962595328 bytes)
  Geometry (BIOS EDD): CHS 58581/254/63
  Size (BIOS EDD): 937426943 sectors
  Geometry (BIOS Legacy): CHS 1024/255/63
  Config Status: cfg=new, avail=yes, need=no, active=unknown
  Attached to: #14 (SATA controller)

31: IDE 1000.0: 10600 Disk
  [Created at block.245]
  Unique ID: WZeP.nkkuEMg7MeD
  Parent ID: Ddhb.FcOdDptW9P4
  SysFS ID: /class/block/sdb
  SysFS BusID: 16:0:0:0
  SysFS Device Link: /devices/pci0000:00/0000:00:1c.1/0000:05:00.0/ata17/host16/target16:0:0/16:0:0:0
  Hardware Class: disk
  Model: "SMvD133509528D80"
  Device: "SMvD133509528D80"
  Revision: "n/a"
  Serial ID: "133509528D80"
  Driver: "ahci", "sd"
  Driver Modules: "ahci"
  Device File: /dev/sdb
  Device Files: /dev/sdb, /dev/disk/by-id/ata-SMvD133509528D80_133509528D80, /dev/disk/by-id/wwn-0x5000c5001feb99f0, /dev/disk/by-path/pci-0000:05:00.0-ata-1.0
  Device Number: block 8:16-8:31
  BIOS id: 0x80
  Geometry (Logical): CHS 58352/255/63
  Size: 937426944 sectors a 512 bytes
  Capacity: 447 GB (479962595328 bytes)
  Geometry (BIOS EDD): CHS 58581/254/63
  Size (BIOS EDD): 937426943 sectors
  Geometry (BIOS Legacy): CHS 1024/255/63
  Config Status: cfg=new, avail=yes, need=no, active=unknown
  Attached to: #22 (SATA controller)
```

And versions of Tendrl packages:
```
tendrl-ansible-1.5.4-1.el7.centos.noarch
tendrl-api-1.5.5-20180202T172550.51b6c71.noarch
tendrl-api-httpd-1.5.5-20180202T172550.51b6c71.noarch
tendrl-commons-1.5.5-20180208T071828.160b4d4.noarch
tendrl-grafana-plugins-1.5.5-20180208T071934.ef4055b.noarch
tendrl-grafana-selinux-1.5.4-20171212T044512.1f5eb63.noarch
tendrl-monitoring-integration-1.5.5-20180208T071934.ef4055b.noarch
tendrl-node-agent-1.5.5-20180202T165439.9e57adf.noarch
tendrl-notifier-1.5.5-20180202T172143.34fc113.noarch
tendrl-selinux-1.5.4-20171212T044512.1f5eb63.noarch
tendrl-ui-1.5.5-20180207T051807.2334615.noarch
```

**Comment by dahorak** [comment]
I was able to reproduce the behavior on our own VMs via following (slightly ugly) trick:
On the Tendrl server, I've created following file `/usr/local/bin/hwinfo` with following content:
```
#!/usr/bin/bash
[[ "$1" == "--partition" ]] && exit 0
/usr/sbin/hwinfo $@
```
And set it executable: `chmod +x /usr/local/bin/hwinfo`

**Please be aware - i is not the original reproduction scenario and it is not intended as a replacement of the original scenario for testing, but it might help with debugging the parsing function on your VMs (without the CentOS CI specific setup).**

**Comment by GowthamShanmugam** [comment]
@nthomas-redhat i need your help here, currently we are maintaining disk and its corresponding partition details in etcd. the problem here is sda is a disk but its block device is not partition type.
it is mpath type. The question here is we need to handle this type also. if yes we need to change current disk structure in etcd.

and hwinfo won't give any detail about this block device. because it is not partition type.

**Comment by GowthamShanmugam** [comment]
Current flow is like, we are collecting disk and partition info from hwinfo using commands
     hwinfo --disk (this will give only disk inf0)
     hwinfo --partition (this will give only partition info)

So here hwinfo is not giving any details about  mpath. 

So we are storing disk details in central store like
        sda {
             disk_id: abc
             partitions: {
                     sda1 info
                         - parent_id: abc (hwinfo gives parent id also)
                     sda2 inf0
                         - parent_id: abc
             }
        }

so when mpath came:
      sda:  {
                partitions: {}   //empty because parent_id is not match
      }

And we are storing all disk id with the disk name in map dictionary, to related lsblk block device output with disk.
From lsblk command, if any block device is partition type then I am using parent name of partition to find disk id in map.

problem is map does not have any parent_name of this partition because.

sda
   - mpath
         - sda1
         - sda2

here sda1 and sda2 partitions immediate parent is mpath, not sda. So it raised KeyError, as per my code all partitions should have disk type parent.

So here we can solve this problem by identifying root parent name of partitions.  but hwinfo what about 
 sda:  {
                partitions: {}   //empty because parent_id is not match
      }  

this device structure which is stored before lsblk command by hwinfo command. there partition is empty.

and one more doubt is need to store mpath also as a block device?

**Comment by GowthamShanmugam** [comment]
i need at least one CentOS CI to debug this problem

**Comment by r0h4n** [comment]
@dahorak @GowthamShanmugam  Any updates on this?

**Comment by GowthamShanmugam** [comment]
@ltrilety Please close this issue

**Comment by dahorak** [comment]
Closing as peer https://github.com/Tendrl/node-agent/pull/740#issuecomment-372252882
