### ISSUE TITLE
Non participating nodes in volume is also pushing the data in graphite

### ISSUE THREAD

**Issue by cloudbehl** [Tendrl/node-agent#730]
The nodes that are not participating in the volume is also pushing the data. so all every volume has all the nodes that are in a cluster is what is getting shown in grafana and graphite.

**Comment by r0h4n** [comment]
@cloudbehl @shtripat @GowthamShanmugam  Is this fixed?

**Comment by GowthamShanmugam** [comment]
Each nodes in a cluster are updating rebalance details in graphite with its own hostname under volume.
Node is not part of that volume but it while pushing rebalance details it creating an entry under all volumes.

Each node in a cluster can push rebalance detail in graphite but storing under its own hostname in volumes entry is wrong.

I feel all nodes should push volume's rebalance  details under tendrl/cluster/{cid}/volumes/, no need to store under tendrl/cluster/{cid}/volumes/nodes/


@shtripat @cloudbehl suggestion please

**Comment by GowthamShanmugam** [comment]
While pushing rebalance details this issue is happening

**Comment by shtripat** [comment]
@GowthamShanmugam can this be closed now?

**Comment by GowthamShanmugam** [comment]
This issue is fixed, we can close this @shirshendu
