### ISSUE TITLE
When node-agent restarted same node details are stored with different fqdn in collectd

### ISSUE THREAD

**Issue by GowthamShanmugam** [Tendrl/node-agent#771]
Initially, in node-agent sync, we are store node_context object with fqdn from the socket.getfqdn(), So monitoring-integration is referring this fqdn and pushing aggregation details into collecting. But in sds_detect we are actually replacing this fqdn with peer hostname. So next time details are pushed using peer hostname only.

So it pushing same node details with different fqdn.

**Comment by GowthamShanmugam** [comment]
@r0h4n @shtripat @nthomas-redhat suggestion please

**Comment by r0h4n** [comment]
Fixed: https://github.com/Tendrl/commons/pull/901

**Comment by r0h4n** [comment]
tendrl-node-agent wont report any fqdn (blank) until it confirms from gluster pool list
