### ISSUE TITLE
Node hardware inventory details

### ISSUE THREAD

**Issue by GowthamShanmugam** [Tendrl/node-agent#78]
Fetch all node hardware inventory details and populate that into etcd. Inventory details required are:
1. Cpu details
2. Memory details
3. Os details
4. Tendrl context details
5. Network details
6. Disk details

**Comment by r0h4n** [comment]
Link this issue to its specification please. This issue is invalid in its current form

**Comment by r0h4n** [comment]
Link this work item to its specification @GowthamShanmugam

**Comment by GowthamShanmugam** [comment]
@r0h4n i have already specified this issue link in specification file

**Comment by brainfunked** [comment]
Where's the pull request for this issue?

**Comment by GowthamShanmugam** [comment]
@brainfunked this issue nothing but disk and network inventory details, already os, memory detail collecting are done, only disk and network is pending

**Comment by GowthamShanmugam** [comment]
@r0h4n we can close this issue
