### ISSUE TITLE
import cluster flow timeout during executing a flow for setup alias for cluster

### ISSUE THREAD

**Issue by GowthamShanmugam** [Tendrl/node-agent#804]
Setup alias job is always in a new state, it is not taken by a monitoring-integration, so import cluster flow is timeout

**Comment by shtripat** [comment]
I feel this is not the scenario we had when it failed. In a croner case when services like tendrl-node-agent and tendrl-monitoring-integration were started back to back very fast and so the server node was not having the tag `tendrl/integration/monitoring`. To tackle this situation we need to make sure at every service sync of the node-agent if tendrl-monitoring-integration found running, it should try to add tag `tendrl/integration/monitoring`.

Does this sound good enough??

**Comment by GowthamShanmugam** [comment]
This issue is fixed, i am closing this

**Comment by GowthamShanmugam** [comment]
This issue is fixed
