### ISSUE TITLE
[documentation] etcd configuration is not referenced

### ISSUE THREAD

**Issue by mbukatov** [Tendrl/node-agent#88]
The [installation.rst document](https://github.com/Tendrl/node_agent/blob/4969c8e9007079ea11005f84f529bccb8a259f09/doc/source/installation.rst) states that `etcd` should be installed first, but doesn't reference any configuration details. It would be good to either do an overview of `etcd` configuration in the document directly, or even better to just reference/link to description of Tendrl etcd configuration from [Tendrl/documentation](https://github.com/Tendrl/documentation) - that said, such description doesn't exist either: https://github.com/Tendrl/documentation/issues/63.

**Comment by sankarshanmukhopadhyay** [comment]
Does the node-agent configuration imply a default configuration of etcd? If yes, this needs to be documented at one single place and kept consistent.

**Comment by r0h4n** [comment]
@TimothyAsir It seems you have to create a PR based on https://github.com/TimothyAsir/documentation/commit/96e5710a4d592320e6487c3101d8ebbdc5c210b2

**Comment by r0h4n** [comment]
This is fixed, please review linked commits

**Comment by mbukatov** [comment]
Proposed overview of etcd configuration for Tendrl is available in branch [etcd-configuration](https://github.com/TimothyAsir/documentation/commits/etcd-configuration), which hasn't been yet merged into master of [Tendrl/documentation](https://github.com/Tendrl/documentation). Neither has been this Tendl wide etcd configuration referenced from anywhere (for obvious reasons).

**Comment by r0h4n** [comment]
Revisiting this now I feel we do not need an "etcd document" or "etcd service configuration reference"

Tendrl specific etcd config changes are documented here https://github.com/Tendrl/documentation/wiki/Tendrl-Package-Installation-Reference

**Comment by mbukatov** [comment]
Ok. I agree, as long as we use single etcd instance running on Tendrl Server machine (as described in Tendrl-Package-Installation-Reference), there is no need to have additional etcd configuration documentation.
