### ISSUE TITLE
[documentation] there are 2 descriptions of tendrl-node-agent installation

### ISSUE THREAD

**Issue by mbukatov** [Tendrl/node-agent#89]
Right now, there are 2 documents which explains installation of `tendrl-node-agent`:

* [doc/source/installation.rst](https://github.com/Tendrl/node_agent/blob/4969c8e9007079ea11005f84f529bccb8a259f09/doc/source/installation.rst)
* [README](https://github.com/Tendrl/node_agent/blob/4969c8e9007079ea11005f84f529bccb8a259f09/README.adoc)

It would be much better to keep this documentation in a single place, rather than duplicate it in 2 documents. I would suggest to move installation documentation out of readme and keep it in installation doc file, while we can refer/link to this file from README.

**Comment by mbukatov** [comment]
When https://github.com/Tendrl/node_agent/issues/90 is fixed, moving pieces of text from README file into doc/source/installation.rst file would be much easier.

**Comment by sankarshanmukhopadhyay** [comment]
There's probably no good reason to have install-configure instructions/sequence of steps in a README. Unless the README precedes the other document and thus means it requires to be made aligned and coherent.

**Comment by r0h4n** [comment]
@TimothyAsir any updates?
