### ISSUE TITLE
Store configuration details in etcd

### ISSUE THREAD

**Issue by GowthamShanmugam** [Tendrl/node-agent#91]
Instead of writing configuration details in file, store everything in etcd

**Comment by mbukatov** [comment]
Is this related to https://github.com/Tendrl/specifications/pull/11/files ?

**Comment by GowthamShanmugam** [comment]
@mbukatov  yes it is related to that

**Comment by r0h4n** [comment]
Link to spec please

**Comment by GowthamShanmugam** [comment]
Tendrl/specifications#11

**Comment by GowthamShanmugam** [comment]
This issue is solved, so i am closing this
