### ISSUE TITLE
[systemd] [question] Service name is tendrl-noded vs name of component and package is tendrl-node-agent

### ISSUE THREAD

**Issue by mbukatov** [Tendrl/node-agent#97]
I noticed that systemd service unit file defines service called `tendrl-noded`, while the name of the package and the binary itself is just `tendrl-node-agent`.  Is there any reason for this discrepancy? Would we break something if the service unit file was called just `tendrl-node-agent.service`?

**Comment by shtripat** [comment]
@TimothyAsir as discussed earlier I think the service should be renamed as tendrl-node-agent.

**Comment by mbukatov** [comment]
Service file has been renamed to `tendrl-node-agent.service`.
