### ISSUE TITLE
[documentation] [question] reference to tendrl-ceph-integration and tendrl-gluster-integration in installation instructions

### ISSUE THREAD

**Issue by mbukatov** [Tendrl/node-agent#98]
I noticed that both `tendrl-ceph-integration` and `tendrl-gluster-integration` are referenced in `README` file of node agent, without further explanation what to do with these components (besides default configuration). 

Based on the already reported issues related to this:
* https://github.com/Tendrl/node_agent/issues/89
* https://github.com/Tendrl/specifications/issues/25

I would assume that content of the README file belongs to installation.rst file (as suggested in  https://github.com/Tendrl/node_agent/issues/89) and that documentation for overall high level installation of Tendrl belongs to `Tendrl/documentation` repo (as suggested in https://github.com/Tendrl/specifications/issues/25). Another evidence suggesting that this is the case is the fact that no interesting details or further reasoning about integration of node-agent and ceph/gluster-integration components are given (right now, it's just clone a repo and copy default config file).

That said, I may be wrong and there may be some reason to reference other components in installation.rst file. If this is the case, this issue is tracking the work on documenting the reasoning of this better, otherwise we could just drop the references to tendrl-ceph-integration and tendrl-gluster-integration from installation.rst file during work on the issues I referenced above and this issue can be closed.

**Comment by TimothyAsirJeyasing** [comment]
Node agent is not depends on gluster-integration or ceph-integration. So all the references and configuration related to any of those packages should be removed from node-agent installation or readme files.

The configuration required for gluster-integration or ceph-integration should be moved to related documents in either gluster or ceph integration packages.

**Comment by r0h4n** [comment]
Can we close this?

**Comment by mbukatov** [comment]
> Can we close this?

The proposed changes hasn't reached current master (commit 39d2dfecc4c40b48d9c9bddc0e71d99dac7abfdc), so I would let it open until that happens. I still see references in the README file:

```
$ find . -name '*.rst' | xargs egrep '(ceph|gluster)[_-]integration'
./README.rst:       $ git clone https://github.com/Tendrl/ceph_integration.git
./README.rst:       $ git clone https://github.com/Tendrl/gluster_integration.git
./README.rst:       $ cp ceph_integration/etc/logging.yaml.timedrotation.sample \
./README.rst:         /etc/tendrl/ceph_integration_logging.yaml
./README.rst:       $ cp gluster_integration/etc/logging.yaml.timedrotation.sample \
./README.rst:         /etc/tendrl/gluster_integration_logging.yaml

```

But it seems that it's being addressed in https://github.com/Tendrl/node_agent/pull/107

```
$ git checkout fix-89 
Branch fix-89 set up to track remote branch fix-89 from TimothyAsirJeyasing.
Switched to a new branch 'fix-89'
$ find . -name '*.rst' | xargs egrep '(ceph|gluster)[_-]integration'
$
```
